ENCODE-DCC/encoded

src/encoded/calculated.py, src/encoded/commands/create_mapping.py, src/encoded/contentbase.py, src/encoded/schema_utils.py, src/encoded/static/components/form.js, src/encoded/static/components/item.js, src/encoded/static/scss/encoded/modules/_facet.scss, src/encoded/static/scss/fontawesome/_icons.scss, src/encoded/tests/test_post_put_patch.py, src/encoded/tests/testing_views.py, src/encoded/types/antibody_lot.py, src/encoded/types/base.py, src/encoded/types/biosample.py, src/encoded/types/dataset.py, src/encoded/types/donor.py, src/encoded/types/experiment.py, src/encoded/views/__init__.py, src/encoded/views/jsonld_context.py
This has the same changes as the 1794-multi-object-forms branch to allow for editing child objects in a form, but doesn't actually link to the forms for any types except page and image.
=> 1794 multi object forms (not enabled)

src/encoded/persona.py
Make sure the user's session has a CSRF token once they've logged in. I think this fixes http://redmine.encodedcc.org/issues/2527
Although, as a side note, I'm puzzled why the /login view appears to not require a CSRF token in the browser but test_login_no_csrf in test_persona.py shows it failing without a CSRF token.
=> make sure user's session has a csrf token as soon as they log in

src/encoded/static/components/inputs/index.js, src/encoded/static/components/inputs/object.js, src/encoded/static/components/item.js, src/encoded/static/scss/encoded/modules/_forms.scss, src/encoded/static/scss/react-forms/_index.scss
This implements http://redmine.encodedcc.org/issues/2547
Note: we're using a separate request to get the item's embedded representation and rendering it using the item's listing view. This means:
- some objects, such as characterizations, don't have a very useful collapsed view yet
- the collapsed view won't update as the form is edited
This also fixes a bug where changing a field to a value that does not pass client-side validation would not update the main form value, so submitting the form would succeed (without the change) rather than show the server validation error.
=> let child object fieldsets be collapsed

src/encoded/static/components/graph.js, src/encoded/static/components/mixins.js, src/encoded/static/scss/encoded/_base.scss
If SVG isn’t available in the current browser, output an error message instead of attempting to render a graph. Mostly applies to IE8. A couple other minor fixes internal fixes as well.
=> Fix graph output in IE8

src/encoded/static/components/audit.js, src/encoded/static/components/inputs/object.js
- call preventDefault for click on audit toggle button so it doesn't trigger a form submit when it's in a form
- intercept clicks on links in the object picker and open them in a new window
=> issue 2664 - fix object picker links in forms

src/encoded/tests/bdd.py
This avoids having to wait for data to load and the browser to start up, then wrinkling your nose in confusion at why some tests were skipped, if you typed "is" instead of "should be"
=> check to make sure bdd steps are found during test collection

src/encoded/static/components/fetched.js, src/encoded/static/components/form.js, src/encoded/static/components/item.js, src/encoded/static/components/search.js, src/encoded/tests/features/forms.feature, src/encoded/tests/features/steps/__init__.py
I set out to fix issue 2748 and found a number of regressions in form functionality, mostly side effects of our changes to work with the newer react-forms library. Here are fixes and some tests.
- Don't try to load the form until persona auth is complete
- Fix bug where re-rendering the form generated a new form schema which ended up triggering an update to the form value, causing child objects to always be sent even when not edited.
- Fix bug where object picker no longer showed the text filter if no search results were found (fixes 2748)
- Fix showing form validation errors from server (react-forms changed the format it expects)
- Fix bug where the schema_version field was not disabled
- Fix bug where editing a child object did not send its id to the server, so the server tried to …
=> Fix various form regressions

src/encoded/audit/experiment.py, src/encoded/audit/file.py, src/encoded/schemas/file.json, src/encoded/schemas/replicate.json, src/encoded/tests/test_audit_experiment.py, src/encoded/tests/test_audit_file.py, src/encoded/types/file.py
This is establishing read_length in the file without taking it out of the replicate.  That part will happen in the large upgrade.
=> Preparing read_length for migration

src/encoded/static/components/browserfeat.js
My test for the existence of canvas assumed too much, and caused an IE8 crash. This fix removes that assumption, and IE8 passes without crashing.
=> 2910 Fix IE8 JS crash

src/encoded/audit/experiment.py, src/encoded/audit/file.py, src/encoded/schemas/file.json
This is basically removing audit code that should have been removed in a previous ticket.  In other tickets this will be obfuscated by data migration, so I removed it now so that Brian could check it out on a demo.
=> cleaning up error from release 25

src/encoded/static/components/pipeline.js
Clicking a step with multiple output types now shows each one on its own line instead of all on one, concatenated by commas. This is a suggestion by Brian Lee on Ticket #2770.
=> Split output_type display to different lines

src/encoded/static/components/item.js
This fixes issue 2950
The travis failure on python 2.7 is the same as the one on master where this was branched from.
=> handle boolean type in schema-based forms

src/encoded/schemas/file.json
reporter code counts, intensity values and transcription start sites.
I think that I inherited the Travis failure from master so I am just going to make the pull request and see what laurence thinks
=> Categorize missing output_types 

src/encoded/audit/file.py, src/encoded/tests/test_audit_file.py
Added an additional file audit as per request in #2948-5
=> Added audit for paired-end run_type without paired_with

src/encoded/static/scss/encoded/modules/_pipeline.scss
This is a low-risk change involving one character in an SCSS file, so it’d be great to get it into Release 26 if possible.
=> 2964 Downloaded graphs have black nodes

src/encoded/static/components/publication.js, src/encoded/static/components/search.js
Hard codes item titles on search result pages instead of using the ones in the columns array. Covers antibodies, biosamples, experiments, targets, datasets, publications, and software; and I’ve made the corresponding changes to the 2975-pipeline-search branch which has titles for pipeline search results.
I guess this can go into Release 27? If you think the changes are fine, you can set the target version of 2990.
=> 2990 Hard code titles in search result pages

src/encoded/static/scss/encoded/_base.scss
For Release 27: blockquote Sizing was too large. Now setting explicitly to the same size as paragraphs.
=> Fix blockquote style

src/encoded/static/components/experiment.js
Now show file_type on Format line instead of file_format.
=> Update experiment graph file details

src/encoded/schemas/pipeline.json
I know that I have been on the arguing side of removing the accessions.  BUT if we are not removing the accessions, I strongly believe that we need replaced.  We have alternate_accessions but I cannot use them.
=> Update pipeline.status with replaced

src/encoded/schemas/target.json
target.gene wasn’t available on the target search page, causing “undefined” in the constructed dbxref URL.
=> Make gene visible on target search page

src/encoded/search.py, src/encoded/static/components/inputs/object.js, src/encoded/static/components/search.js
When entering an object for a linkTo property, if no object is currently selected a text input is now shown. On blur it will search for the entered text and open the search panel.
I tried to make the focus work nicely for keyboard input. (You can tab onto the 'x', hit enter to remove the current value, then enter a search term and hit enter to search, then hit enter to accept the first result.)
I also made sure the 'uuid' field is always searched (we made sure it's included in all mappings even if not explicitly listed as a boost value).
=> 2747: better UI for object picker input

src/encoded/audit/file.py
Upgrading read_length audit to ERROR and including ENCODE2 and ENCODE2-mouse
=> 3069 read length audit error

base.ini, buildout.cfg, candidate.cfg, production.ini.in, setup.py, src/contentbase/attachment.py, src/contentbase/storage.py, src/encoded/commands/migrate_attachments_aws.py, src/encoded/tests/test_download.py, src/encoded/tests/test_storage.py, src/encoded/types/file.py, src/encoded/upgrade/document.py, versions.cfg
This is not quite ready to merge but I've made good progress and wanted to give @lrowe a chance to look it over.
If the blob_bucket setting is set, we use an s3-backed BlobStorage implementation; otherwise the old rdb-backed one. The s3-backed storage falls back to the rdb-backed one for stored files with no bucket name stored.
Outstanding questions:
- Is there a reliable way to tell when we're behind a proxy and should use X-Accel-Redirect? The existing code in types/file.py checked for an Origin header, which wasn't there when I was testing access via the dev nginx. The X-Forwarded-For header set by nginx is swallowed by the PasteDeploy prefix middleware. For now I am comparing the port from the Host header to the SERVER_PORT to see if they differ, but that feels hacky.
- What buckets …
=> 3038: s3 attachments

src/contentbase/jsonld_context.py, src/encoded/commands/check_files.py, src/encoded/commands/jsonld_rdf.py, src/encoded/static/components/antibody.js, src/encoded/static/components/biosample.js, src/encoded/static/components/collection.js, src/encoded/static/components/dataset.js, src/encoded/static/components/form.js, src/encoded/static/components/item.js, src/encoded/static/components/target.js
Various changes to show more related items on views of biosample, donor, and target:
- refactored a bunch of form-related code into form.js instead of item.js
- add a description column for biosamples
- tweaked the collection table component so it can be rendered without a header and with customized columns
- add a RelatedItems component which does a search and renders a limited collection table of results with a link to the full resultset (or renders nothing if there are no results)
- refactored existing uses of ExperimentTable to use RelatedItems
- added a full page view of donors
=> 3228 related items

src/encoded/static/components/antibody.js, src/encoded/static/components/globals.js, src/encoded/static/scss/encoded/modules/_characterizations.scss
For [Redmine 3259](http://redmine.encodedcc.org/issues/3259), [Release 33](http://redmine.encodedcc.org/versions/90)
* On the antibody pages in the characterization panels, now displays “Submitter comment” that displays ```antibody_characterization.comment```, and “Reviewer comment” that displays ```antibody_characterization.notes```.
* Added CSS classes for exempt-from-standards statuses, both for the new exempt status circle as well as the exempt status badge for antibody characterization documents.
=> 3259 UI display for antibody exemption status

src/contentbase/schema_views.py, src/encoded/static/components/form.js, src/encoded/static/components/inputs/object.js, src/encoded/static/components/item.js, src/encoded/static/scss/encoded/modules/_forms.scss
This addresses ticket 2548 by showing fields for which the user lacks permission as disabled inputs.
It also fixes ticket 3214 by no longer filtering those fields out of the schema served at /profiles/
=> 2548 readonly form fields

src/contentbase/elasticsearch/indexer.py, src/encoded/commands/es_index_listener.py
Does not fix the same problem caused by ``wal_level hot_standby``: http://www.postgresql.org/message-id/CAOycyLTc0+jtJhsTOs5i7gJLEuKW_Y8yxBQms0yXY12HxemfBA@mail.gmail.com
=> Tweak so that we do not trigger new xids unnecessarily.

src/encoded/static/components/app.js
Added an “Ontologies” menu item to the “Help” menu that points to an anchor on the existing /help/getting-started page. This also required adding this anchor to that page, which @aditin14 did.
=> 3307 Add Ontologies menu

src/encoded/schemas/dataset.json, src/encoded/static/components/audit.js, src/encoded/static/components/dataset.js, src/encoded/static/components/search.js
Now displays the usual status badge and audit indicators below the title on dataset pages.
Now displays the status and audit indicators on dataset search results, below the accession.
=> 3284 Dataset audit and status display

src/encoded/static/components/biosample.js, src/encoded/static/components/dataset.js, src/encoded/static/components/experiment.js, src/encoded/types/biosample.py, src/encoded/types/donor.py
The biosample, experiment, dataset, human donor, and mouse donor pages can now display links to their PMID: and doi: references. When they appear, they link to the appropriate ENCODE publication page which itself has links to PubMed or source page as appropriate.
The references get displayed as their own line item in the summary panel of these pages.
=> 1415 Links to references

src/encoded/static/components/experiment.js
Overlooked bad reference to ```jsonGraph.filterOptions``` on experiments with no file graph. Causes a browser console output ```Unhandled promise rejection TypeError: Cannot read property 'filterOptions' of null(…)``` for any experiment that doesn’t display a file graph.
=> 2978 filterOptions fix

src/encoded/static/components/experiment.js
I had been using an older property of the React synthetic events to get the currently selected item, which worked everywhere except IE — in IE, the currently selected filtering item came up with “undefined.” Now using the proper property that works across all browsers.
=> 3421 Fix IE graph filtering bug

src/encoded/schemas/library.json
Also capitalized DnaseI to DNaseI. No libraries currently use that enum in the data.
=> Add RNaseIII to fragmentation enums

src/encoded/schemas/talen.json, src/encoded/static/components/talen.js
Supply columns to TALEN schema so that listing has data to display. I hope adding columns to the schema doesn’t cause reindexing. Doesn’t seem like it should, but I’m not sure.
=> TALEN search result crash fix

src/contentbase/indexing_views.py
If the basic permissions of system.Everyone or system.Authenticated are allowed other permissions are irrelevant.
Roles are intermediaries, never directly given to users.
=> Simplify indexed permissions.

src/encoded/static/components/biosample.js
The ```source``` and ```rnai.source``` objects of a biosample could have a ```title``` property but no ```url``` property. Previous code didn’t take this into account and put an ```<a>``` there regardless, causing a link that didn’t go anywhere. This branch changes this to check for ```url``` properties, and simply display the ```title``` without the link if no ```url``` property exists.
=> 2595 biosample links

src/encoded/static/components/dataset.js
Ticket [3512](http://redmine.encodedcc.org/issues/3512)
For all Series-type Dataset pages, now displays Lab, Award PI (when available), and Project in the top-most summary panel.
=> 3512 Add Lab, Award PI, and project to Series pages

src/encoded/schemas/reference_epigenome.json, src/encoded/static/components/search.js
For [Redmine 3520](http://redmine.encodedcc.org/issues/3520): Search result pages show all targets associated with any of the Series types of datasets: reference epigenome, organism development, matched set, replication timing, treatment concentration, and treatment timing
=> 3520 Series search result target display

src/encoded/static/components/biosample.js, src/encoded/static/components/dataset.js, src/encoded/static/components/sorttable.js
Donors used by more than five biosamples now show the biosample table with a footer showing the number displayed and the total number, and a *View all* button if the total is more than five. Also makes the *View all* button smaller than before to fit the footer better.
=> #3456 Fix missing View All button for biosample tables

src/encoded/schemas/reference_epigenome.json
Search results with ReferenceEpigenome objects now display:
Reference epigenome series in _biosample_term_name_
…for the linked title. This makes it the same as the other Series dataset search results.
=> 3556 ReferenceEpigenome search result biosample_term_name

src/contentbase/resource_views.py, src/encoded/renderers.py, src/encoded/tests/test_views.py
Return a 404 Not Found instead returning None causing a later error to be thrown.
=> Fix bad frame name

src/encoded/static/components/__tests__/antibody-test.js, src/encoded/static/components/antibody.js, src/encoded/static/scss/encoded/modules/_characterizations.scss
Primarily a bug fix to show the caption which I oddly gated on whether I had calculated an excerpt from a long caption or not. It now gates on whether the caption exists or not.
Also fixed ticket 3504 where the caption would sometimes get pushed off the panel, disappearing.
Also fixed an unreported styling problem where the drop-down data had no padding with the edge of the panel.
=> 3587 antibody characterization captions

src/contentbase/elasticsearch/create_mapping.py, src/encoded/schemas/biosample.json, src/encoded/schemas/construct.json, src/encoded/schemas/dataset.json, src/encoded/schemas/document.json, src/encoded/schemas/mixins.json, src/encoded/schemas/page.json, src/encoded/schemas/pipeline.json, src/encoded/schemas/talen.json
removed raw indexing from every 'description' and 'notes' field of every schema object. Also, page object's layout.blocks.body is not being raw indexed.
=> 3360 remove raw indexing from large fields

src/encoded/static/components/biosample.js
This display used to key off an @type of “characterization,” but with the @type casing change, this test failed. It now instead keys off “Characterization.”
=> 3626 Make biosample characterization captions appear again

src/encoded/schemas/biosample.json, src/encoded/schemas/experiment.json
This is part of removing raw indexing from certain fields. There was a use case for searching the notes, and notes needed to be boosted.
=> 3360 boosting notes in biosample and experiment objects

npm-shrinkwrap.json, src/encoded/static/components/graph.js
First fix involved integrating a change from dagre-d3 author Chris Pettit for handing the issue. The second fix involved changing our code to clear the graph before redrawing it on changes, like from changing the filter.
=> 3663 Chrome 48 doesn’t draw graphs properly

src/encoded/loadxl.py
Reverts ENCODE-DCC/encoded#1144
This fails because lack of tests/data/inserts, we'll bring it back later this week.
=> Revert "Update loadxl.py"

src/encoded/static/components/experiment.js, src/encoded/types/file.py
I focused so much on getting the placeholder display right, I forgot to get the display of the normal case right. master now doesn’t show an information panel when you click a contributing file. This fixes that, as well as removes contributing_files from the experiment.py embed because the Javascript doesn’t use it anymore.
=> 3611 Fix contributing file oversight

src/encoded/static/components/form.js
This fixes the infinite recursion bug discussed in http://redmine.encodedcc.org/issues/3724 which breaks editing biosamples in the current RC
=> don't show more than one level of children objects on forms

src/contentbase/etag.py, src/contentbase/storage.py
This is enabling infrastructure to make check_files more robust in the face of user changes to the file it is checking.
=> Make etag record tid of all propsheets.

src/encoded/static/components/doc.js, src/encoded/static/components/experiment.js, src/encoded/static/components/search.js, src/encoded/static/components/sorttable.js
React key warnings have been building up. This commit fixes all of them except for the usual Nav one which isn’t in our control right now.
=> 3328 Fix React key warnings

src/snowfort/etag.py
make sure browser always revalidates schemas, in case user changed and has different permissions
=> 3758: fix caching of /profiles/

src/encoded/audit/file.py, src/encoded/tests/test_audit_file.py
fixing the audit of read depth to rely on the QC metric rather than on derived from FASTQ run)type property
=> 3769 read depth fix

src/encoded/static/components/form.js
This fixes http://redmine.encodedcc.org/issues/3822 where submitters could not add items because the form was including default values for readonly fields.
=> don't include readonly fields in form default

src/encoded/static/components/form.js
This fixes http://redmine.encodedcc.org/issues/3834 and also avoids unnecessary data transfer.
=> forms: don't load child objects until they are expanded

src/encoded/static/components/dataset.js, src/encoded/static/components/publication.js, src/encoded/static/components/search.js, src/encoded/static/components/target.js
Target gene links did not expect to find an array of dbxrefs, and made a malformed URL from it. It now searches for the first MGI: dbxref and makes a link from that.
=> 3807 Use first MGI: in list for mouse targets for gene link

src/encoded/tests/data/inserts/user.json, src/snovault/crud_views.py
(the deleted item is not present in the request, and the use of `i` here worked only because the variable was left in scope from above)
=> 3871: show error re deleted item on parent node

src/encoded/static/components/app.js, src/encoded/static/components/audit.js, src/encoded/static/components/search.js
Implement a single switch that enables/disables the display of audits while logged out. It’s disabled in this build, so merge if needed.
=> 3989 Hide audits while logged out

src/encoded/static/components/dataset.js, src/encoded/static/components/experiment.js
Dataset-derived objects were using their own files array only for their file tables. Now they do file searches just like Experiments do.
=> 4019 Use file searches for dataset types

src/encoded/static/components/dataset.js, src/encoded/static/components/experiment.js
* If the user is logged in and the dataset is released or release ready, it performs a search of files that refer to the dataset. These get combined with files in the dataset itself to produce the final set of files.
* If the user is logged out or the dataset isn’t released or release ready, only the files within the dataset itself make the final set of files — no search is performed.
=> 4019 Display files for each dataset type

src/encoded/static/components/antibody.js
They were stuck in the pointing-down direction. They now respond to clicks property, pointing left until clicked, whereupon they point down.
=> 4006 Display document and characterization disclosure triangles properly

src/encoded/static/components/experiment.js
Stop assuming chip-seq QC attachments exist. This caused the Javascript to crash on click when they didn’t.
=> 4073 Some green QC circles in the graph aren’t clickable

src/encoded/static/components/dataset.js, src/encoded/static/components/filegallery.js
Now use a flag to indicate whether to draw a graph or not, and all dataset object types use the same table/graph display component, but with some choosing to not display the graph.
=> 4099 Display file gallery on all dataset pages

src/encoded/static/components/filegallery.js
When an experiment/annotation has a file table and/or graph but has no filtering menu, the up/down arrows for it still appeared. This change removes that by a small rearranging of JSX so that the entire <div> for the menu doesn’t get rendered when the menu’s not needed, not just the menu itself.
=> 4130 Eliminate unnecessary arrows with no filtering menu

src/encoded/static/components/experiment.js
Had been grouping them by library, but obviously this doesn’t work with no library. Now we don’t group at all if there’s no library.
=> 4086 Replicate table with two biological replicates and no library

src/encoded/static/components/audit.js
Simply made the regex more flexible. Handles surrounding non-space characters, as well as links at the beginning and end of audit text.
=> 4249 audit links handle surrounding punctuation

src/encoded/static/components/globals.js, src/encoded/tests/data/inserts/fly_donor.json
#4263 - added missing linkout to BDSC stock number dbxrefs in fly donors
=> Add linkout for BDSC dbxrefs

src/encoded/batch_download.py, src/encoded/schemas/changelogs/file.md, src/encoded/schemas/experiment.json, src/encoded/schemas/file.json, src/encoded/schemas/matched_set.json, src/encoded/schemas/organism_development_series.json, src/encoded/schemas/project.json, src/encoded/schemas/publication_data.json, src/encoded/schemas/reference.json, src/encoded/schemas/reference_epigenome.json, src/encoded/schemas/replication_timing_series.json, src/encoded/schemas/treatment_concentration_series.json, src/encoded/schemas/treatment_time_series.json, src/encoded/schemas/ucsc_browser_composite.json, src/encoded/tests/data/inserts/file.json, src/encoded/types/file.py
Passes local schema tests.
https://4300-mapped-read-length-f2e81e5-jseth.demo.encodedcc.org/
Functional tests documented here:
http://redmine.encodedcc.org/issues/4300#note-7
=> Add mapped_read_length property to file object

src/encoded/types/dataset.py
Various dataset types now display their library accessions in the raw file table. Before, the libraries weren’t embedded, so the accessions weren’t available.
=> 3829 dataset raw file tables

src/encoded/types/biosample.py
biosamples with part_of set display their parent’s documents. Not all document types for part_of were embedded, leading to a Javascript crash. This branch embeds the needed documents for part_of.
=> 4352 biosample part_of causing Javascript crashes

src/encoded/static/components/search.js
Was assuming that query string for audits would always be something like “audit.ERROR.category=something” but wasn’t taking things like != into account. Redmine #4404.
=> 4404 Stop assuming audit URL form

src/encoded/batch_download.py
Also worked around Excel not opening single-column TSV files with “ID” as the header text.
=> 4426 Fix ID column selector on report view

src/encoded/static/components/genetic_modification.js, src/encoded/tests/data/inserts/genetic_modification.json
Treat genetic_modification.source and genetic_modification.source.alias as optional.
=> 4330 Stop expecting optional properties in genetic modification objects

src/encoded/static/components/filegallery.js
These bugs are caused by the previous in-memory value of a derived_from flag passed between iterations of rendering the graph. The same fix fixes both tickets.
=> 4536 / 4535 File graph change bugs

src/encoded/schemas/experiment.json, src/encoded/schemas/publication.json, src/encoded/search.py, src/encoded/static/components/search.js, src/encoded/tests/test_search.py
This adds a concept of facet types. In addition to the default 'terms' facet, it implements an 'exists' facet which will present yes/no options based on whether the object has any value for the field. It also handles linking those to field=* and field!=* in the search query string, which are turned into exists/missing filters in the elasticsearch query.
I also brought over some tests and refactoring of the search code that I had originally done for the hierarchical facets work, which got stalled.
=> 4085 boolean existence facet

src/encoded/static/components/typeutils.js
Used to be biosample.protocol_documents. Affects both biosample and experiment displays.
=> 4537 Get biosample docs from biosample.documents

src/encoded/static/components/search.js
This was an odd leftover from David’s original homepage_summary branch I had inadvertently left in. This change reverts his experimental changes.
For Release 49
=> 4554 Allow 0-count facet terms to be clickable again

buildout.cfg, src/encoded/static/components/app.js, src/encoded/static/components/home.js, src/encoded/static/scss/encoded/modules/_home.scss
This branch only affects the home page. The original algorithm for the charts involved destroying the chart each time new data came in, and creating the charts fresh. This caused the charts to vanish and redraw as the user chose new selections of assay and organism (each causing a GET request).
In addition, the FetchedData component — that has existed in encoded probably since the beginning of the ReactJS implementation — redraws whatever data it retrieved the last time before doing the GET request. That caused the charts to redraw an extra time. I looked into avoiding this initial redraw, but I could only see having FetchedData clear its past data and rendering nothing before doing the GET request (React components have to render immediately). That reduced one chart redraw, but caused …
=> 4519 Stop multiple redraws on the home page charts

etc/encoded-apache.conf
i have added the block for POST PATCH and PUT to the encode-apace.conf. By default, it has been commented out. this was tested on a server Idan brought up and was successful.
=> Adding PUT/PATCH/POST forbid to encode-apache.

src/encoded/static/components/mixins.js
For some reason Auth0 requests the site logo twice; the first time with the proper URL and the second with the incorrect one. This branch changes the mixin.Auth0 code to return the complete URL of the icon instead of just the local path. It does this by parsing the current URL to extract the hostname, port, and protocol, and combining that with the logo file’s path.
Apparently, the Auth0 code caches the URL, because with this change, the logo gets requested only once on instances, and twice on local ones. Local instances no longer give a 404 error on the second request.
=> 4590 prevent logo 404

src/encoded/static/components/filegallery.js
New modal code was calculating files to graph like before based on archived status, but then not using that calculation. It was _checking_ the unused variable, so it passed eslint.
=> 4959 Use files w/o archived files when assembling grpah

src/encoded/search.py
This fixes the visibility button for searches, making it dependent upon at least one released experiment.  The visibility button on matrix results does is not dependent on released experiments (unfortunately).
=> 4576 visibility button for trackhubs

src/encoded/static/components/graph.js, src/encoded/static/components/mixins.js, src/encoded/static/inline.js
Looks like I’m behind a long Travis CI queue, so I’ll issue the PR before this branch’s Travis CI has started. I removed the $script reference to the persona script, and removed a couple other unused references to the scriptjs module that were likely optimized out during build.
I kept the $script.path link as it does have a function, and I’m not sure if removing it breaks anything, because we still use scriptjs in richtext.js. Most uses of scriptjs went away with webpack, and I’m guessing richtext.js can stop using it. Maybe with David Glick’s forthcoming update to react-forms, that’ll go away unless there’s some needed functionality in scriptjs we lose with webpack’s require.ensure.
=> 4671 Remove stray persona reference

src/encoded/static/components/search.js, src/encoded/static/scss/encoded/modules/_facet.scss, src/encoded/tests/features/search.feature
* The <Facet> component now checks for the existence of non-zero data in the facet before attempting to display it.
* Converted the CSS table code for horizontal facets to use flexbox instead, as I’ve been doing for several other parts of the code for better consistency and easier maintenance. This does cause a rendering difference at some browser widths, where columns that would have taken half the horizontal space now stretch to the full width of the enclosing space. Here’s an example with the Experiment matrix.
* To work with flexbox, I found it convenient to add an extra div with the class “orientation” between the “box facets” div and the “facet” div. This caused one of the BDD tests that looks for box.facets > facet to break. I updated that test to account for the extra div: …
=> 4680 matrix gap between horizontal facets

src/encoded/static/components/dataset.js, src/encoded/static/components/filegallery.js
All Dataset-derived pages use the same graph/file code that I refactored for modals and restricted files — except for Series dataset objects that call that code at a lower level because they show different sets of column headers for their file tables. I didn’t change this code to keep up with the new data the file table code expected, so it tried to reference properties of properties that didn’t exist, and so we got a Javascript crash.
The standard graph/file code now checks to be sure that data’s there before dereferencing it, so that the new features simply won’t be used if the caller doesn’t pass the information for them, such as the Series objects don’t.
=> 4682 Fix Javascript crash when displaying series objects with files

src/encoded/static/components/filegallery.js
I _used_ to display file.title, but somewhere along the way I forgot and only displayed file.accession. This branch returns to displaying file.title in dataset file tables as well as the title bar of QC modals, because those display their parent file accessions.
=> 4684 Switch to using file.title instead of file.accession

src/encoded/static/components/filegallery.js
That was embarassingly stupid. Part of converting string arithmetic to string templates for AirBnB compliance, I got the variables mixed up.
=> 4697 Flip file size units and value

src/encoded/schemas/experiment.json, src/encoded/schemas/matched_set.json, src/encoded/schemas/organism_development_series.json, src/encoded/schemas/project.json, src/encoded/schemas/reference_epigenome.json, src/encoded/schemas/replication_timing_series.json, src/encoded/schemas/treatment_concentration_series.json, src/encoded/schemas/treatment_time_series.json
This purely involves removing the `files.analysis_step_version.analysis_step.pipelines.title` facet from all dataset-derived schemas: experiment, matched_set, organism_development_series, project, reference_epigenome, replication_timing_series, treatment_concentration_series, and treatment_time_series.
=> 4745 Pipeline facet removal

src/encoded/static/components/file.js
Originally, the file page did a search including the term `derived_from.accession` that equaled the accession of the file being viewed. Because derived_from isn’t embedded anymore, this always gave zero results. I now search for the term `derived_from` instead, as that’s now a list of @ids.
=> 4780 file pages now show panel with a table of files deriving from the displayed one

src/encoded/static/components/file.js
Now displaying content_error under the label “Content error detail” on file pages.
=> 4650 content error

src/encoded/static/components/dataset.js, src/encoded/static/components/experiment.js, src/encoded/static/components/file.js, src/encoded/types/dataset.py, src/encoded/types/experiment.py
Also de-embedded supersedes from Annotation and Experiment as they appear not to be needed. I use the @id to get the accessions for display.
=> 4777 Collect and display supercedes accessions

src/encoded/static/components/globals.js
When experiment and some other dataset pages display, they do a search of files to display on the graph and file tables. The list of files needed had to increase to include “content error” files so they would display in the file tables too.
=> 4833 Add content error files to list of files searched

src/encoded/static/components/filegallery.js
Datasets that should never show graphs were still showing the information buttons on the file tables, and clicking them brought up no modal. That’s because datasets without graphs were still generating graphs — just not showing them.
This change makes datasets that don’t show graphs not generate them either, so their information buttons don’t appear because they’re based on files that actually appear in a generate graph.
If there’s a v53rc2, this should go in. If not, it should be OK to wait for v54 because it just shows buttons that don’t actually work, but has no other consequences.
=> 4871 Datasets with hidden graphs showing info buttons

src/encoded/static/components/graph.js
We had assumed all style sheets have rules, but in the case of having the Privacy Badger Chrome extension installed, you can have an empty style sheet. Also removed some unused property declarations.
=> 4869 Stop making CSS style sheet assumptions

src/encoded/static/components/doc.js, src/encoded/static/scss/encoded/modules/_panels.scss
Small change to the flexbox CSS styles, and a little renaming to [BEM](http://getbem.com/introduction/) standards, as I’ve been very slowly transitioning to.
=> 4906 document subpanel wrapping in Safari

src/encoded/static/components/search.js
Some new biodalliance-related code used a new `assemblies` prop to the `ResultTable` component. While regular /search/ results add this prop, form code doesn’t, and really shouldn’t have to. This change makes it so we check for their existence before using it.
Also fixed some incorrect prop types that caused React warnings.
=> 4985 Javascript crash when clicking form Browse button

src/encoded/static/components/dataset.js, src/encoded/static/components/filegallery.js, src/encoded/static/components/objectutils.js
Temporarily pass a boolean property from the component for the dataset objects so that we know it came from a non-experiment dataset (I improperly called annotationSource before I realized it affected other datasets) which I’ll remove for 56. This boolean along with a check for fly/worm assemblies disables the Quick View button. I’ll also remove the fly/worm check for 56 or whenever that issue gets resolved.
=> 4533 Disable Quick View for fly/worm assemblies and dataset-derived types

src/encoded/static/components/objectutils.js
Just added mm9 to a list of assemblies for which we disable Quick View. Presumably, this whole mechanism will go away once these assemblies have genes in them (though the email from Alec makes me wonder?).
=> 4533 Disable Quick View for mm9

src/encoded/search.py
In addition to `used_facets`, this change has `format_facets` also compile a list of facets for which the "exists" property…exists. Then to determine whether a “fake” NOT facet should be suppressed (as it should with "exists" facets), it also checks whether the facet being tested is in this set before suppressing it.
=> 4970 Bring back the NOT facet

src/encoded/audit/file.py, src/encoded/tests/test_audit_file.py
In our effort to remove as many as possible File audits, here we are removing audit_file_pipeline_status audit. It was flagging released files associated with non-active pipelines. Audit test was removed as well. The mission to detect these files moved into “releasenator” script from pyencoded tools.
=> removing inactive pipeline audit from file

src/encoded/schemas/file.json
The `file_type` and `read_length_units` properties were removed from the `columns` property of the file.json schema in [this commit](https://github.com/ENCODE-DCC/encoded/commit/1de6f10effed3a8a918acdb55fd272f8b9a11351). The dataset-page file tables use searches to get their data, so with this schema change that data went away, leading to blank “File type” displays, and corrupted “Read length” displays. Experiment [ENCSR000AEN](http://localhost:6543/experiments/ENCSR000AEN/) on a local instance provides a good demo of this while logged in or not within the annotated highlight:
This commit just returns these two properties to the schema so that the tables display correctly again:
=> 5059 Fix display issues in file tables

src/encoded/audit/file.py
removing missing_flowcell_details audit in our effort to get rid of as many file audits as possible. Wranglers are not finding this audit useful.
=> 5060 missing flowcell

src/encoded/static/components/filegallery.js
This bug fix addresses a highly unusual but possible situation in which an experiment page can partially render file tables, and the console shows a Javascript crash.
You can use the experiments @aditin14 modified on test and my demo.
To reproduce the bug, you need:
* an experiment with one and only one biological_replicate value
* replicates with no library reference
* paired sequencing files, e.g. paired fastq files, that refer to that replicate and experiment.
You should expect to see the replicate table with empty library and biosample columns, and a “Raw sequencing files” table showing your paired files.
With [ENCSR089CCK on test](https://test.encodedcc.org/experiments/ENCSR089CCK/) while logged in:
For this situation, the code references `file.replicate.library.accession` without …
=> 4998 Fix file table display when replicates have no libraries

src/encoded/audit/file.py, src/encoded/tests/test_audit_file.py
Removing audit checking for file derivation from revoked files. it is a duplication of an audit on item.
=> removing derived_from_revoked duplication audit from FILE

src/encoded/static/components/search.js
v56rc1 never shows audits on search result pages in the facet list while logged out, though they still appear on individual items that have them. Previous behavior always shows audit facets while logged in or logged out except for audit.INTERNAL_ACTION.category audits which only display while logged in.
I caused this during my removal of unused React context variables. We introduced one a while ago that prevented the display of audits while logged out. Once we got the approval to display them, I set this variable to false permanently. When moving to React 15, I removed this variable completely, but incorrectly changed an if statement during facet display that used it, causing any audit facets to always fall through to the case where no facet gets displayed.
1. Go to to the demo to URI …
=> 5069 audit facets don’t display while logged out in v56rc1

src/encoded/static/components/app.js
5074 IE11 page-change alert
encoded taps into the browser's `onbeforeunload` event to insert a message into the page-contents-changed alert before navigating away from a page. The `<App>` component keeps an `unsavedChanges` state variable that gets updated with references to fields that have been modified when editing an object. `unsavedChanges` gets checked when our `onbeforeunload` handler gets called, and we either return a string to cause the warning alert to appear with that string, or "null" for the alert to not appear.
This turns out to be out of spec. You’re supposed to return nothing (undefined) when you don’t want the alert to appear. To most browsers, this didn’t matter. To Trident (IE11 but not MSEdge) browsers, this did.
The only modification to fix this was to remove the …
=> 5074 IE11 page-content-change alert

.eslintrc.json, npm-shrinkwrap.json, package.json, src/encoded/static/components/audit.js, src/encoded/static/components/file.js, src/encoded/static/components/item.js
I’m not clear why this problem only seemed to show up for replicate JSON pages, but the bug stems from an npm module I started using with React 15 to generate unique IDs. One of the AirBnB React rules involves not using Javascript loop indices as React component keys. [This article](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318) suggested using the “shortid” npm module to generate a unique ID instead of using the loop index. The problem is that shortid can generate different values on the server and client, so when loading a page you end up with an invariant violation because the corresponding client- and server-generated HTML had different keys.
I considered hashing each audit object to generate an ID that would be the same on both server and client, but …
=> 5071 React error when displaying replicate JSON pages

src/encoded/static/components/search.js
This probably resulted from a merge error. The condition for empty doc_counts was removed for v55, but since 4755-react-15 branched before then, it kept it through subsequent merges, and got merged back into master.
1. Go to any search page (e.g. "/search/?type=Experiment”).
1. nter a facet term to the URL with a `!=` operator (e.g. “/search/?type=Experiment&assay_title%21=DNase-seq”).
1. The bottom facet in the facet list should show that term with the bang after the title, but with no count.
=> 4790 Fix vanished “not” facets

src/encoded/static/components/filegallery.js
This problem resulted from two different but physically close bugs.
1. Using the same React key in both an inner and outer rendering loop when rendering a raw file table. React complains if you use the same component key twice within a loop, and using the same key in nested loops caused the inner loop’s components to all have the same key. I fixed this by changing the component to use file.@id as the key because that has guaranteed uniqueness.
2. Displaying an array of `<td>` components within a conditional expression. This used to work in React 0.12, but apparently not with React 15. I switched this code to use the same kind of method I used in `<RawSequencingTable>` — render each component within its own conditional expression.
1. Find an experiment page with a Raw file table. An …
=> 5070 Fix raw file table bugs

src/encoded/static/components/filegallery.js
This was fixed and merged earlier, but it appeared again in v56rc2 because of a similar problem in a different spot. The original issue happened while grouping paired files by replicate/library. That was fixed for v56rc1.
Why this didn’t appear at this spot until now, I’m not sure. The code did shift position between v56rc1 and v56rc2, but it’s the same code run under what I _think_ are the same circumstances.
The fix involves simply checking for the existence of a replicate and its library before retrieving the library’s accession.
=> 4998 Fix assumption of replicate library’s existence

src/encoded/static/components/antibody.js, src/encoded/static/components/biosample.js, src/encoded/static/components/experiment.js, src/encoded/static/components/filegallery.js, src/encoded/static/components/genetic_modification.js, src/encoded/static/components/pipeline.js, src/encoded/static/components/publication.js, src/encoded/static/components/search.js, src/encoded/static/components/software.js
This problem stemmed from modules not adapting to the new audit mechanism quite as readily as I had thought. With the Javascript mixin-shaming that the React team has engaged in, I had converted the audit module from an extensive mixin system to use High-Order Components (HOCs) instead.
Javascript mixins have the convenient feature of assimilating all the characteristics of the components they’re used in, including React props and states, and React context objects. They were able to use the encompassing component’s importing of _encoded_ login session information to get the user’s current login state.
With the transition to HOCs, this mechanism no longer works. The audit module’s wrapping of the components that use it means they share no props, state, nor React context. This left the …
=> 5101 DCC Internal Audits not rendered regardless of login state

README.md
Small update to README:
- `brew link --force` is required to make some packages "findable"/executable from from the commandline without manually modifying user's `.bash_profile`
- Added `brew link --force postgresql@9.3`
=> 5053 update readme addition

src/encoded/__init__.py, src/encoded/schema_formats.py, src/encoded/tests/data/inserts/file.json, src/encoded/tests/test_accession_replacement.py, src/encoded/types/base.py
encoded/schema_formats.py contains some jsonschema.FormatChecker objects that are supposed to validate particular fields (type: accession, type: uuid, type: gene_name, etc.).    This module was not getting imported at the right time and the FormatChecker was not picking them up.
This PR includes tests for the operational formatcheckers (accessions and uuid) and with Laurence's help I managed to get the imports in the right sequence.
Note that the change to file.json is just to allow that file to be loaded, as it had an invalid accession!
To test this you can try to patch/put an existing accession; it must  correspond to the RE: '^ENC(FF|SR|AB|BS|DO|LB|PL)[0-9][0-9][0-9][A-Z][A-Z][A-Z]$' in production or ^TST(FF|SR|AB|BS|DO|LB|PL)[0-9][0-9][0-9]([0-9][0-9][0-9]|[A-Z][A-Z][A-Z])$' in a demo …
=> 5111 update accessions

src/encoded/audit/file.py, src/encoded/tests/test_audit_file.py
currently missing derived_from audit is triggered for revoked/deleted/replaced files, when they are derived from revoked/deleted and replaced files. This behavior started after application of audits on all Files (without dependency on their status). To fix this situation and not trigger the audit - it was modified to not flag deleted/revoked and replaced files that are derived from these statuses.
=> (5132) modifying derived_from audit to accept derivation from revoked deleted files for revoked deleted files

src/encoded/static/components/search.js, src/encoded/types/dataset.py
The back end controlled whether the Quick View button could render or not based on the user’s logged-in state, so the primary change happened in dataset.py which now doesn’t check the logged-in state before offering the Quick View data in the `visualize` calculated property.
search.js also checked the logged-in state to decide whether to draw the tabbed search results or not. This check was similarly removed so that it always displays when requested regardless of logged-in state.
=> 5151 Remove biodalliance login restriction

src/encoded/static/components/blocks/search.js, src/encoded/static/components/search.js
Editing search fields in forms caused Javascript errors. I had updated search.js to AirBnB/ES6 and updated most of the references to it, but forgot about files in components/blocks. This updates components/blocks/search.js to import things the correct way, and also now exporting ResultTable from search.js as this file needs it.
=> 5070 Fix search import/export for forms

src/encoded/schemas/file.json
fixing in File.json the dataset linkTo property, it was a list without a real reason, so I turned it back into a single link instead.
=> ENCD-3387 (RM5200) fixing dataset linkTo in File.json

src/encoded/static/components/region_search.js
Unconditionally removed this button/menu. I don’t like commented-out code in Github, so we can restore this code later from Github history.
=> ENCD-3420 Remove Download Elements button

src/encoded/static/components/filegallery.js
We often (and AirBnB forces us to) use stateless components where component properties come from `props` instead of `this.props`. In this place I forgot to convert our old stateful implementaiton with 1this.props1 to the new stateless implementation as 1props1. Fixed this by using `props` instead of `this.props` in that component.
=> ENCD-3426 Fix improper use of this.props

src/encoded/static/components/item.js
AirBnB prohibits using variable names matching parent scope variable names, including the global scope. Because `url` already existed in the global scope from the `url` npm package, I had to change that to `itemUrl`. Unfortunately, I forgot to change that usage within the calling <RelatedItems> component.
=> ENCD-3427 Fix changed property name

src/encoded/static/components/biosample.js
This restores a previous PR that I closed because I found another bug that caused the biosample page construct section to not display construct documents. Kath looked at this and found the bug accidentally produced the correct behavior — we don’t _want_ construct documents appearing in the constructs section because we display construct documents in the Documents panel anyway.
So I reverted this change and went back to the original PR. It’s a bug that exists there, but a harmless one. We should probably clean that up at some point.
From my original PR: Not sure why I deleted the tag display code with the AirBnB update. It’s back now, and badder than ever — it now uses an arrow function callback as AirBnB requires.
=> ENCD-3431 construct tags

.travis.yml, src/encoded/tests/data/inserts/image.json, src/encoded/tests/data/inserts/user.json
Added Kriti Jain and Keenan Graham to users.json so they can log in locally. I also fixed images.json test data because those objects still referred to Cricket’s old email address, so that caused local demos to run into validation errors.
This branch also has ENCD-3435-remove-2.7-from-travis merged in, so it does _not_ perform the Python 2.7 test on Travis CI.
=> New users for local instance login

.travis.yml, src/encoded/static/components/globals.js, src/encoded/tests/data/inserts/image.json, src/encoded/tests/data/inserts/user.json
This was another AirBnB conversion bug caused by the rule against mutating parameters. I changed the routine to truncate strings to copy the incoming parameter so I could mutate that at will, but then returned the original parameter string just like it used to. This changes it to return the mutated, truncated string. I also merged my “new-users” branch so that local instances can start up without validation errors, as well as the ENCD-3435-remove-2.7-from-travis branch.
=> ENCD-3437 truncation incorrect

.travis.yml, src/encoded/static/components/pipeline.js, src/encoded/tests/data/inserts/image.json, src/encoded/tests/data/inserts/user.json
Until release 58, I had no access to a version number for analysis steps in the pipeline graph. Now with the `major_version` and `minor_version` properties, I do have access to `analysis_step.major_version` from the pipeline graph modals, and this branch now displays it in the modal header. The `minor_version`, while accessible, is an array with no indication of which minor version to display, so that remains undisplayed.
=> ENCD-3433 Show version number in pipeline graph modals

.travis.yml, src/encoded/static/components/filegallery.js, src/encoded/static/components/globals.js, src/encoded/tests/data/inserts/image.json, src/encoded/tests/data/inserts/user.json
This branch simply updates the `assemblyPriority` array that we use to sort GRCh38-minimal behind GRCh38. I also fixed a bug I found while testing in that Reference dataset objects showed a blank Assembly/Annotation menu because I set the default value for that menu to an empty string instead of the “default” string it should have had.
I also merged in my “new-users” branch so that local instances can start up without validation errors as well as the “ENCD-3435-remove-2.7-from-travis” branch.
=> ENCD-3419 Update assembly order in graph drop-down

src/encoded/tests/data/inserts/user.json
Including timezone now causes server startup errors. PRing this before Travis CI is done because I need to catch the bus before it’ll be done.
=> ENCD-3464 Remove timezone from local user test data

src/encoded/static/components/filegallery.js, src/encoded/static/scss/encoded/modules/_characterizations.scss, src/encoded/static/scss/encoded/modules/_pipeline.scss
This update just changes the color of missing files. There’s also one more CSS change I haven’t yet looked into why I needed. It seemed I must have deleted a line of CSS with the document disclosure buttons, so they didn’t appear correctly though they still worked correctly.
=> ENCD-2704 file graph updates

src/encoded/static/components/__tests__/experiment-test.js, src/encoded/static/components/award.js, src/encoded/static/components/experiment.js
Many of the changes are just slight source-code styling changes, and very small ones. The main change here was reversing the released and submitted variables so that each one receives the right data.
The change for the cumulative chart not only involved changing the colors to avoid the transparent ones, which also meant changing the order of the data given to chart.js so that the submitted chart wouldn’t hide the released chart now that they’re not transparent. That’s why you see the change to the array of objects to `new Chart`.
Also in this branch is the addition of a “Date submitted” display in the experiment page summary box, and a reformatting of the date to display in MMMM D, YYYY format instead of the existing YYYY-MM-DD format. The data hasn’t changed — just the display.
=> ENCD-3436 Updates/corrections for award pages

src/encoded/static/components/pipeline.js
The `assay_term_name` string property no longer exists in pipeline objects. Instead, `assay_term_names` exists and is an array of strings. This led to these changes:
1. The Pipeline page summary panel now shows “Assays” instead of “Assay,” and it shows a comma-separated list of `assay_term_names` elements.
1. Pipeline object search results also displayed `assay_term_name` in the little summary. It now displays a list of `assay_term_names` comma separated.
1. The breadcrumbs at the top of the pipeline page now shows the assay_term_names elements separated by a plus sign, as AntibodyLot pages have done for a while. Clicking it brings up a search page with all the displayed assay_term_names selected in the facets. If no assay_term_names are available, then no breadcrumbs get displayed at …
=> ENCD-3512 pipeline assay_term_names update

src/encoded/static/components/filegallery.js
I had already made these changes, but don’t know what happened to them. The modals were based in the graphing function which worked when there was always a graph, but not when there’s sometimes a graph. This moves the modal to a parent component, so we have no new code — just code that’s moved from a child component to the parent so that both tables and graphs share the state that brings up the modal.
=> ENCD-3516Restore info button

src/encoded/static/components/app.js, src/encoded/static/components/home.js
This affects the Encyclopedia Matrix and Search menus, as well as the Computational Predictions button on the home page.
=> ENCD-3519 Change all Annotation searches from version 3 to 4

src/encoded/schemas/pipeline.json, src/encoded/static/components/pipeline.js, src/encoded/types/pipeline.py
Adds a non-required property to the pipeline schema that links to a page in the DB. This property, if it exists for a particular pipeline object, gets displayed in the summary panel of the pipeline’s individual page.
=> ENCD-3472 Link to pipeline standards pages

src/encoded/static/components/biosample.js, src/encoded/static/components/genetic_modification.js, src/encoded/static/scss/encoded/modules/_key-value-display.scss
* Removed the construct and RNAi sections from the summary panel.
* Changed the `reagents` display on the GM pages so that they each display on their own line instead of all smooshed together like they appear on production now. This applies regardless of whether they’re linked or not.
=> ENCD-3571 updates to the genetic modification UI

src/encoded/static/components/filegallery.js, src/encoded/static/scss/encoded/modules/_forms.scss, src/encoded/static/scss/encoded/modules/_panels.scss
No longer gating both the assembly/annotation menu _and_ the inclusion checkbox based on the existence of more than one assembly and/or annotation. The inclusion checkbox now always gets displayed. This also involved adding a new CSS style because the inclusion checkbox always expected the assembly/annotation menu to its left.
=> ENCD-3587 filtering

src/encoded/schemas/worm_donor.json, src/encoded/static/components/__tests__/dbxref-test.js, src/encoded/static/components/dbxref.js
NBP is currently unused, and duplicated by NBRP, so I removed it from front-end processing, as well as the schema.
=> ENCD-3489 Remove NBP from dbxrefs

src/encoded/static/components/dbxref.js
Accidentally removed this dbxref prefix for v62rc3. Maybe a good way to demonstrate that new dbxrefs in this new system are very easy to add, as long as they’re easy URLs at least.
=> ENCD-3489 Restore RefSeq dbxref

src/encoded/audit/experiment.py, src/encoded/tests/test_audit_experiment.py
Submitting for Idan. Uploading files return _file in uploading state_ audit instead of _file validation error_ audit.
=> ENCD-3578-content-eror-audit

src/encoded/audit/file.py, src/encoded/audit/item.py, src/encoded/schemas/changelogs/publication.md, src/encoded/schemas/publication.json, src/encoded/tests/test_audit_file.py, src/encoded/tests/test_audit_item.py
This changes the logic for the missing derived_from audit. Before the raw files in the derived_from field of BAMs were only counted if they were FASTQs with the same status as the BAM _or_ if they were not deleted, replaced, revoked. This led to undesirable triggering of audit in some cases. For example:
- BAMs that came from CSFASTA/CSQUAL/FASTA instead of FASTQ.
- Deleted BAMs that came from revoked FASTQs.
Now raw files (still excluding tars) are counted if they have a higher or equal status-level value compared to BAM, based on STATUS_LEVEL dict in audit/items.py:
Have also added tests of the audit to tests/test_audit_file.py.
=> ENCD-3595-missing-derived-from-audit-refactor

.travis.yml, README.md, buildout.cfg, cloud-config-cluster.yml, cloud-config.yml
PR for fixing the inconsistent buildout and setup tools version.  
The updated version
zc.buildout==2.9.5
setuptools==18.5
=> Encd 3648 fix buildout setuptool versions

src/encoded/tests/test_upgrade_publication.py, src/encoded/upgrade/publication.py
This gets rid of batchupgrade errors of Publication objects in cloud-init-output.log (Publication schema version bump requires upgrade function).
=> ENCD-3646-fix-publication-upgrade

src/encoded/upgrade/dataset.py
Checks that annotation_type field is in object first (ten Annotation objects are missing annotation_type field, causing batchupgrade error).
=> ENCD-3649-annotation-type-batchupgrade-fix

src/encoded/schemas/file.json
files with output_type "reads" and "rejected reads" should not be allowed to specify "assembly"
=> ENCD-3609 updating file.json dependency

src/encoded/static/components/__tests__/experiment-test.js, src/encoded/static/components/antibody.js, src/encoded/static/components/biosample.js, src/encoded/static/components/dataset.js, src/encoded/static/components/donor.js, src/encoded/static/components/experiment.js, src/encoded/static/components/file.js, src/encoded/static/components/item.js, src/encoded/static/components/objectutils.js, src/encoded/tests/data/inserts/file.json
All components that display the `alternate_accessions` property now call a new React component called `<AlternateAccession>` that takes an array of `alternate_accessions` strings and outputs elements meant for below the header line on individual object pages.
The modification to file.json test data was because I noticed that object had two `file_size` properties in it, so I got rid of the first one since the second would override it.
=> ENCD-3637 Change alternate accessions display

src/encoded/static/components/form.js, src/encoded/types/biosample.py, src/encoded/types/dataset.py, src/encoded/types/donor.py, src/encoded/types/experiment.py, src/encoded/types/file.py, src/encoded/types/genetic_modification.py
This also includes 2 related changes:
1. Rename calculatedProperty to notSubmittable which is a better description of its meaning
2. Add support for hiding a property from the forms without preventing submission using hideFromForms
=> ENCD-3669 Specify reverse link properties which should not be submittable

src/encoded/schemas/file.json
ENCD-3673 new output_type for de-identified bams (dbGaP)
* Added new output_types for bams: redacted alignments and redacted unfiltered alignments.
=> ENCD-3673 Add new redacted output_types

src/encoded/audit/file.py, src/encoded/tests/test_audit_file.py
This checks if the list of quality metrics in a file is redundant based on the following signature which should be unique: 
`(analysis_name, assay_term_name, file_format, output_type, @type[0], processing_stage)`
For example a BAM should only have one of these:
`('ChIP-seq', 'bam', 'bwa-alignment-step-v-1', 'unfiltered alignments', 'SamtoolsFlagstatsQualityMetric', 'filtered')`
This avoid comparing numerical values between metrics to see if they are duplicates, which misses cases where the metrics are the same but the values are different.
On demo:
=> ENCD-3740-duplicate-quality-metric-audit

src/encoded/audit/experiment.py, src/encoded/audit/item.py, src/encoded/static/components/award.js, src/encoded/static/components/item.js, src/encoded/types/base.py, src/encoded/visualization.py
Remove a few more mentions of proposed and preliminary statuses where they are no longer needed. You'll still find them mentioned in changelogs and upgrades but this is expected.
=> ENCD-3707-scrub-proposed-preliminary

src/encoded/visualization.py
Third PR is a charm?  This can be patched to es5-master and vis_cache reindexed.  That should fix the trackhubs failures.
=> [ES5] ENCD-3746 Fix pop error

cloud-config-cluster.yml, cloud-config-elasticsearch.yml, cloud-config.yml, src/encoded/commands/deploy.py
Change to merge with v64rc4
This PR
- adds the deployer's ssh key to the cloud-config through deploy.py string format templating
- fixes pylint issues in deploy script
- removes key signing from all cloud configs
- download an authorized_keys file from an s3 bucket that should contain everyone's ssh key.
This will move the deployer's ssh key into authorized_keys2 as a backup but this will only work with dsa and rsa keys.  The s3 authorized_keys is written to ~/.ssh/authorized_keys.
=> ENCD-3656 include ssh keys in deploy

src/encoded/audit/experiment.py, src/encoded/audit/file.py
escalating the audit from DCC_ACTION to WARNING for:
1. file upload/validation errors
2. file inconsistent assemblies
=> ENCD-3734 file audit escalation

src/encoded/audit/item.py, src/encoded/schemas/changelogs/publication.md, src/encoded/schemas/publication.json, src/encoded/static/components/testdata/publication/PMID16395128.js, src/encoded/static/components/testdata/publication/PMID23000965.js, src/encoded/tests/data/inserts/publication.json, src/encoded/tests/features/generics.feature, src/encoded/tests/test_upgrade_publication.py, src/encoded/types/base.py, src/encoded/upgrade/publication.py
Changes include:
- reduced enums to in progress, released and deleted
- bumped up the schema_version number to 6 and updated changelog
- added an upgrade to migrate existing statuses to new statuses
- added upgrade test, updated fixtures and generic features test
- scrubbing/updating in preparation and published statuses elsewhere in the codebase
=> ENCD-3708 Update publication states

src/encoded/static/components/search.js
When displaying the list of facets, now check both the term _and_ the facet.field against the search results filter to make sure we’re not matching the same term from a different facet. This prevents the 0-count term from displaying only because it happens to have the same term value as one in the /search/ query string.
=> ENCD-3724 Adjust facet term display check

src/encoded/batch_download.py
Issue: Line 310 and 318 throws a stack trace when 'files' key is not present in the dict, 'exp'
Fix: Add an 'if block' and filter out the entries that do not have 'files' key
AWS Instance: http://ec2-52-36-22-200.us-west-2.compute.amazonaws.com/ has the fix
=> ENCD-3579, ENCD-3473 - Batch download isues

src/encoded/schemas/annotation.json, src/encoded/schemas/biosample.json, src/encoded/schemas/experiment.json, src/encoded/schemas/organism_development_series.json, src/encoded/schemas/project.json, src/encoded/schemas/publication_data.json, src/encoded/schemas/reference.json, src/encoded/schemas/reference_epigenome.json, src/encoded/schemas/replication_timing_series.json, src/encoded/schemas/treatment_concentration_series.json, src/encoded/schemas/treatment_time_series.json, src/encoded/schemas/ucsc_browser_composite.json, src/encoded/search.py
There are basically two changes in this branch:
1. Add “award.name” to the boost values of the schemas of all objects we wanted to appear when searching for an associated award name.
1. Make awards searchable by adding it to DEFAULT_DOC_TYPES in search.py.
Because this affects searching, I also merged this change into an ES5 branch as a test, and found it works the same way as it does in ES1.7 with no changes. This branch is ES1.7 though.
=> ENCD-3741 Search for objects based on associated grant number

src/encoded/schemas/histone_chipseq_quality_metric.json, src/encoded/schemas/idr_quality_metric.json
Typo in schema title for histone_chipseq_quality_metric.json was changed from "Histione" to "Histone".
=> ENCD-3795 Fix spelling in histone and idr qm jsons

src/encoded/tests/test_search.py
just changes the aggregation "size" parameter in tests to be in line with deployment.
=> ENCD-3815 Fix tests for facet aggregation set to 200

src/encoded/static/components/report.js, src/encoded/static/libs/bootstrap/modal.js, src/encoded/static/scss/encoded/modules/_report.scss, src/encoded/static/scss/style.scss
I used the existing Modal module used in several other places of the portal. Mostly this involved changing the existing ColumnSelector component to bring up this modal instead of the drop-down menu. I use the Modal in self-managed mode rather than plug-and-play mode so that its set of selected columns can be updated on mount — in plug-and-play mode, the modal doesn’t get mounted and unmounted as it gets displayed and dismissed, leaving its state with the selected columns potentially behind the reality coming from the URL query string.
I removed the toggleColumn method from the Report component because the columns no longer update as you select which columns you want to include or not. Instead a new setColumnState method gets called when the Modal gets dismissed, with the new set of …
=> ENCD-2567 New report page column selector modal

src/encoded/static/components/home.js, src/encoded/static/components/matrix.js
We no longer need to take the Computational Prediction option to decide whether to use experiment.biosample_type or replicate.library.biosample.biosample_type — we now always use experiment.biosample_type. That lets us properly link from the home page chart to the matrix. Also, fix a React warning caused by having biosample_type and biosample_term_name having the same text value, something we’ve not had before.
=> ENCD-3421 Properly link home chart to matrix

src/encoded/static/components/report.js
When displaying the report, stringify any values of type object to make them appear as JSON in the table.
=> ENCD-3456 Stringify array and object items in a cell

README.md
Split from ENCD-3815 fix test search  #2112
=> ENCD-3827 Fix ES5 version in README

src/encoded/schemas/biosample.json, src/encoded/schemas/changelogs/biosample.md
Added PMI and PMI_units properties to biosample.json, along with dependencies to limit its use to tissue biosamples and only in tandem. Also removed tissue biosamples from culture_start and end date properties inappropriately included in that dependency.
=> ENCD-3820 Biosample: PMI property

src/encoded/audit/experiment.py, src/encoded/audit/standards_data.py
(1) the minimal threshold of 3M was moved to be 5M for everything except H3K9me3 where it was moved to be 100.
(2) the maximal insufficient threshold for broad marks was lowered from 40M to 35M
(3) the low read depth control audit that cold not be called (>20M but <45) moved into INTERNAL_ACTION
=> ENCD-3757 Adjust histone broad peak read depth audit

src/encoded/audit/experiment.py
replacing the use of platform names by platform IDs in the audit code
it resolves previously erroneous detection of HiSeq2K and 2.5K as inconsistent platforms
=> ENCD-3835 Fix inconsistent platforms audit HiSeq2K 2.5K

README.md
Reverts ENCODE-DCC/encoded#2117
Accidentally merged this to master instead of dev
=> Revert "ENCD-3827 Fix ES5 version in README"

src/encoded/audit/biosample.py, src/encoded/schemas/biosample.json, src/encoded/schemas/changelogs/biosample.md, src/encoded/tests/datafixtures.py, src/encoded/tests/test_audit_biosample.py
Adds nih_institutional_certification property to biosample and triggers audit if field missing for human ENCODE4 samples.
=> ENCD-3698 Add Institutional certifications to biosample

src/encoded/schemas/namespaces.json, src/encoded/static/components/__tests__/dbxref-test.js, src/encoded/static/components/dbxref.js
Same as https://github.com/ENCODE-DCC/snovault/pull/80, but affecting both static links and code, that generates new links. Greetings!
=> ENCD-3882 Update DOI preferred resolver url

src/encoded/static/components/schema.js, src/encoded/static/scss/encoded/modules/_schema.scss, src/encoded/static/scss/style.scss
Most of the change involves the new `<DisplayObjectSection>` component that replaces a loop inside `<DisplayObject>`. Now that each displayed section needs to keep its own state for being open or closed, it needed its own component to track that, and react to clicks in the new button.
I also added aria properties so that people using screen readers can better tell what they’re doing when opening and closing these sections. I should have added those to the open/closed state of the individual properties originally too.
=> ENCD-3841 Add collapsing sections on schema pages

src/encoded/search.py, src/encoded/static/components/report.js, src/encoded/static/scss/encoded/modules/_tables.scss
* This branch does not require any snovault modifications, but search.py now imports TEXT_FIELDS from snovault. This is a list of encodeD properties that are configured as text fields in Elasticsearch and thus can’t be sorted without causing the problem that prompted this ticket.
* `set_sort_order` uses TEXT_FIELDS to decide whether to include a property in the Elasticsearch query sorting property. `search` calls `set_sort_order`, and `report` calls `search` to do most of the grunt work. So even if one of the properties in TEXT_FIELDS gets specified for sorting in the query string, they won’t get sorted.
* `search` also passes the contents of TEXT_FIELDS up to the front end with a new `non_sortable` property of search results, which the front end’s report function reads to know whether to …
=> ENCD-3854 Fix report description column sort error

src/encoded/audit/experiment.py
missing unfiltered alignments audit should be triggering only on ENCODE produced processed files. In this ticket we fix incorrect triggering for non ENCODE processed files
=> ENCD-3899 Fix exp audit trigger on non-encode pipelines

src/encoded/static/components/schema.js, src/encoded/static/scss/encoded/modules/_schema.scss
This PR relies on SNO-26-json-extension.
The most key new function is `collectLinks` which digs into schema properties looking for linkTo/linkFrom properties at any embedded levels and making arrays of all those properties it could find of each kind. These then get displayed as links.
The other part (relying on SNO-26) involves doing a GET request on the new /profiles-map/ object through the <FetchedData>/<Param> components, which then gets used to convert whatever properties `collectLinks` found to the corresponding schema paths.
=> ENCD-3840 Add link to linkFrom linkTo schema properties

src/encoded/audit/biosample.py, src/encoded/audit/experiment.py, src/encoded/tests/test_audit_biosample.py, src/encoded/tests/test_audit_experiment.py
This moves nih_institutional_certification audit from biosample to experiment. Will trigger on any ENCODE4 experiment that is using biosample missing nih_institutional_certification field.
=> ENCD-3894 Move NIH cert audit to experiment

src/encoded/tests/data/inserts/file.json
This updates one piece of test data so that the tests won't break once `encoded` is updated to a release of `snovault` that includes https://github.com/ENCODE-DCC/snovault/pull/85 (we can no longer have multiple references to the same object in a property marked with `uniqueItems: true`)
=> ENCD-3891 Fix file test for duplicates in derived_from

src/encoded/batch_download.py
- Issue: metadata_tsv route fails when experiment_json object doesn't have the 'files' key
- Fix: Default 'files' to an empty list when there is no 'files' key
=> ENCD-3916 Fix for broken metadata queries

src/encoded/batch_download.py, src/encoded/tests/test_batch_download.py
This PR addresses the comments from the previous PR for the same tickets:
ENCD 3823 - Filter out restricted files
ENCD 3864 - Refactor batch_download methods
ENCD 3868 - Add unit tests for batch_download helpers(partially implemented)
Demo: https://encd-3823-batchdownload-restrcited-016edb3f0-karthik.demo.encodedcc.org
Reference #2127
=> ENCD [3823, 3864, 3868] - filter restricted files, batch_download refactor, add unit tests

src/encoded/batch_download.py
* The fix is basically adding the already seen values to the 'seen' set()
Demo: https://encd-3863-eliminate-repeated-values-in-report-tsv-155bb34cd-karthik.demo.encodedcc.org
(Note: This is a bug which got introduced while fixing ENCD-3473 Fix for unknown error in batch_download)
=> ENCD-3863 Eliminate repeated values in report TSV

checkfiles/deploy.py, src/encoded/commands/deploy.py
Changed default ami in deploy scripts to use c5 and m5 series.  Way faster (and cheaper!)
=> ENCD-3886 Update deploy machine instance types

src/encoded/tests/data/inserts/library.json
branch is slightly misnamed but it's not the barcode that was failing the REGEX but the plate location
=> [3RD] ENCD-3934 fix plate location in library

src/encoded/schemas/experiment.json
Due to the code duplication, dependencies didn't work and single cell was not possible for specification in experiment biosample_type
=> [2ND] ENCD-3935 Remove duplicated code in dependency of experiment schema

src/encoded/static/components/biosample.js, src/encoded/static/components/donor.js, src/encoded/static/components/genetic_modification.js
The basic cause of this problem is that I had expected DocumentRender to be called even if the GM/characterization document search 404ed, but it doesn’t.  So if the GM had no documents of its own, and none of the GM characterizations had documents, then no GM characterizations would appear. If even one document existed, then they would all appear. All the local test data either had no characterizations or some with documents, so it always checked out.
To fix this, instead of using `<FetchedData>` to retrieve the documents, I use `requestSearch` which does a search GET request for document objects that’s promise based, then sets a couple of states with the results of the GET request which causes the document panels to update with the results along with the embedded characterizations.
=> ENCD-3973 Redo how GM characterization documents get displayed

src/encoded/static/components/__tests__/status-test.js, src/encoded/static/components/antibody.js, src/encoded/static/components/statuslabel.js
The core of this change is to filter AntibodyLot.characterizations (embedded on antibody pages) by status based on your current logged-in and admin states, and I extend my past half-hearted attempt at status revision which now seems necessary to provide in some form in ENCD-3629.
You can still see unreleased antibody characterizations in the JSON, but for now the team feels this is acceptable until and unless we figure out something better than a front-end-only change.
Where this Jest test will go eventually, I don’t know. Probably it’ll just be a kind of random sample of types, or just these two.
=> ENCD-3216 Hide antibody characterizations via user access level

src/encoded/schemas/experiment.json, src/encoded/tests/test_batch_download.py
Just adds the new column to experiment.json so it appears on type=Experiment report pages, and adjusted the corresponding test to expect this new column.
=> ENCD-3957 Add biosample accession to report columns

src/encoded/schemas/samtools_flagstats_quality_metric.json
=> ENCD-4010 fixing a typo in the samtools flagstat quality metric

src/encoded/static/components/experiment.js, src/encoded/static/components/filegallery.js
The largest change involves removing the `anisogenic` boolean that I had been passing around before, and instead just using `context.replication_type` to determine what to display in table column headers. I added a function that takes `replication_type` and returns a string appropriate for table headers.
=> ENCD-3867 Display proper replicate_type string

src/encoded/schemas/changelogs/target.md, src/encoded/schemas/target.json, src/encoded/static/components/testdata/lot_review.js, src/encoded/static/components/testdata/target/HNRNPA1-human.js, src/encoded/tests/data/inserts/target.json, src/encoded/tests/test_upgrade_target.py, src/encoded/upgrade/target.py
Moves target statuses to standard_status mixin.
=> ENCD-3871-target-standard-status

src/encoded/static/components/footer.js
Added the link for privacy in the footer, and not including the auth0 update which will happen in another branch. I did change the `<Footer>` component to get rid of one eslint exception, but I kept the other exception because it would involve a fair amount of small changes here and there — easy for a release but a bit much for a hot fix.
=> ENCD-4045 Add privacy link to footer

src/encoded/static/scss/encoded/modules/_key-value-display.scss
Firefox and other browsers have slight differences. For example, Firefox adds an extra dash if the word breaks on a dash while Chrome does not. But essentially, all evergreen browsers and IE11 should be the same.
=> added hypen for long words

src/encoded/static/components/matrix.js
This is a bit tricky. I gave the th in this fix a "min-width" so that it does not wrap to an unacceptable width as can occur if given merely a "width"-style. I am not sure why the style is inline rather than through a css-class (in multiple places). However, I believe that is a discussion behold the scope of this bug.
=> ENCD-4058-expanding-matrix-creates-unaligned-headers-on-the-x-axis

src/encoded/vis_defines.py
Fix was tested on demo: https://reg-41-inital-region-indexing-failure-2a0200d8a-tdreszer.demo.encodedcc.org/experiments/ENCSR425LSX/
=> ENCD-4073 Revert accidental blocked dataset status expansion

webpack.config.js
After upgrading auth0-lock in ENCD-4045 with their fixes for this problem, we still see the same problem with the superagent npm package. I fixed this by adding superagent to the list of directories that gets processed by babel to convert ES6 used in superagent to ES5 that uglify requires in this version of webpack.
A demo isn’t needed for this ticket. To test this, you need to do a clean build and then look at the webpack output to see that the error message copied into the ticket doesn’t appear.
=> ENCD-3728 Fix build error

src/encoded/region_indexer.py
Fixes the initial region indexing bug, which turned out to be a race condition in handing off the staged uuids list.  Tested this solution on a demo, (but had to artificially open the race condition window wide to catch it).
=> ENCD-4093 Fix initial region indexing failure

.gitignore, src/encoded/static/components/app.js, src/encoded/static/components/home.js, src/encoded/static/libs/bootstrap/tooltip.js, src/encoded/static/scss/encoded/modules/_home.scss, src/encoded/static/scss/encoded/modules/_tooltip.scss
Two new search fields feature on the home page in place of the descriptive text next to the ENCODE assay category selector image. One simply copies the functionality of the search field in the upper right of every page. The other uses the SCREEN website in two ways:
1. To perform a search of a given term
2. To suggest search terms given a partial search term.
The vast majority of the changes exist in home.js including the new forms and nascent code for a combobox — a combination text-input field an drop-down list. I filed ENCD-4121 to refactor this combobox to its own module. I also filed ENCD-4120 to refactor other components to use the tooltip.js module this branch introduced.
=> ENCD-4017 Fulfill ECP requests for home page additions.

src/encoded/static/scss/encoded/modules/_facet.scss
This is tricky. Re-writing the HTML to use grid-system would require a lot of testing (I think is ideal) since this code is reused a lot and in many ways. Lowering accession-class (left hand side of table) would also be tricky. The safe-bet is rise the right-hand-side to be higher than left. I did a light search and I could not find a place where that would be a problem,
=> ENCD-4144 Fix failing impersonation test button size

src/encoded/loadxl.py, src/encoded/tests/__init__.py, src/encoded/tests/features/conftest.py
This allows bin/test to be called with a --log arugment which will limit the logging output from loadxl.load_all when called from tests.features.conftest.workbook.
Create and troubleshooting tests with that use workbook is a little slow and painful.  This will limit the scroll back in a backwards compatible manner.
=> ENCD-4149 Allow bin test log arg for workbook loading

src/encoded/static/components/file.js
Added a constructor to `<FileDownloadButton>` so that `this` is defined properly in `onMouseEnter` and `onMouseLeave`. I don’t know how this ever worked before, but it definitely did for some reason.
=> ENCD-4146 Restore FileDownloadButton constructor

src/encoded/schemas/changelogs/organism.md, src/encoded/schemas/organism.json, src/encoded/tests/data/inserts/organism.json, src/encoded/upgrade/organism.py
ENCD-4152 Make organism.scientific_name required
* Made Organism.scientific_name required
* Bumped schema version and updated change log
* Added empty upgrade to reflect version bump
* Fixed an organism insert to have scientific_name property
=> ENCD-4152 Make organism.scientific_name required

src/encoded/search.py
Ben or I could not find where this search_type arg was ever used.  It can't be added as a query parameter because it wasn't set up properly.  Is was in the way for search refactor epic so we're removing it.
SNO-46 for similar snowflakes updates.  Please review along with this.
https://github.com/ENCODE-DCC/snovault/pull/122
=> ENCD-4154 Remove unused search type arg

src/encoded/audit/experiment.py, src/encoded/tests/test_audit_experiment.py
adding file output type "peaks and background as input for IDR" to the "peaks" files being audited in experiment.py
=> ENCD-4123 audit chip

src/encoded/region_atlas.py, src/encoded/region_search.py
Create a "regulome-summary" view for multiple regions input for region search. It should first parse the input and find unique regions. If it ends up with only one unique region, it will redirect to the "region-search" view. Otherwise, it returns a summary in `result['summaries']` which is a list of regulome search results including `chrom`, `start`, `end`, `rsids`, `regulome_score`.
=> REG-49 Multi-region search backend

src/encoded/static/components/search.js
Update for already-merged PR. With this update, the cart toggle button only appears with experiment search results. With RC1 they appear on the search results of all dataset-derived types (FileSet, PublicationData, etc). Carts only support experiments. The toggle button already doesn't appear on non-experiment dataset-derived object pages, so that part’s fine.
=> [2nd] ENCD-3159 Remove cart toggle from dataset results

src/encoded/static/components/matrix.js
Clicking the biosample_term_name in gray on the left column, or clicking individual matrix cells, now includes the biosample_type for that group in the query string for the search page that you go to when you click either of those.
=> ENCD-4239 Add biosample_type to query string on matrix click

etc/encoded-apache.conf
The redirect from /files/ to /search/?type=file caused the /files/#!add mechanism to fail. “files” is the only object type that gets redirected, and according to Bek he thinks Ben wanted this because our old /files/ page killed the system. As our new /files/ page with the charts doesn’t kill the system, we can go back to _not_ redirecting.
=> ENCD-4267 Remove files redirect from apache config

src/encoded/static/components/dataset.js, src/encoded/static/components/experiment.js, src/encoded/static/components/typeutils.js
I moved ExperimentTable and its dependencies from dataset.js to typeutils.js, and I moved ControllingExperiments from experiment.js to typeutils.js. This is to avoid the possibility of having circular imports, and that’s the purpose of typeutils.js — to have React components and functions that are specific for encode object types but could get shared between related types. In this case, both Series and Experiments could both rely on the same ControllingExperiments component, which depends on ExperimentTable.
=> ENCD-4231 matched set controls

src/encoded/static/components/__tests__/objectutils-test.js, src/encoded/static/components/biosample.js, src/encoded/static/components/dataset.js, src/encoded/static/components/donor.js, src/encoded/static/components/experiment.js, src/encoded/static/components/objectutils.js, src/encoded/tests/data/inserts/human_donor.json
* I replaced a lot of duplicated code with a new InternalTags component that’s in objectutils.js, as the HTML generation is a bit more complicated with the links.
* I feel like these new `<a>` should have title attributes to help explain to sighted users what these buttons will lead to, but the vast majority of a11y sites say to never use title attributes as they might get read by some screen readers, duplicating the alt attribute on the `<img>`, so I didn’t use the title attribute. I’m thinking this is something yet to be worked out in the industry.
* Fixed a couple eslint errors in objectutils.js.
* Removed the internal_tags checks for `<FlyWomDonor>` and `<MouseDonor>` because only HumanDonor has `internal_tags` as a property.
=> ENCD-4223 Make internal_tags badges clickable to search pages

src/encoded/tests/test_status_trigger.py, src/encoded/types/file.py
Avoid making any ACL calls when setting status on restricted files.
=> ENCD-4245-skip-restricted-acl

buildout.cfg, src/encoded/commands/generate_ontology.py, src/encoded/docs/updating_ontologies.md
forced 'mint-chip-seq' to shim to 'dna binding' assay category as it was noticed in v78rc1 that it was no longer shimming to the assay category due to some updated at OBI
regenerated ontology.json, uploaded it to aws, updated buildout to look for the new ontology.json
=> [2nd] ENCD-4195 update ontology with mintchip slimming

src/encoded/static/components/file.js, src/encoded/static/components/filegallery.js
Quality metrics objects get embedded in File objects regardless of their status. Until this branch, all quality metrics objects from a File search appear in the File `@graph` array. This branch changes the front end to filter out non-released status quality metrics objects if the user is logged out. This includes quality metrics in the file association graph as well as in the modal that appears when you click on a file in the graph or from the “i” button in the file tables. Non-released quality metrics objects appear in the JSON even if you’re logged out, and that will be addressed more generally in another ticket.
=> ENCD-4263 Only show released quality metrics

src/encoded/static/components/app.js, src/encoded/static/components/search.js, src/encoded/static/components/summary.js, src/encoded/static/scss/encoded/modules/_facet.scss, src/encoded/static/scss/encoded/modules/_summary.scss
This commit should fix 2 issues:
(1) when you select facets and then type in Search bar and then go back, the last facet you selected is not saved in the history
(2) when you select facets, the list of facets jumps down to display "Clear facets" - the jumping can cause you to click on the wrong thing while you are making selections
=> ENCD-4297 Fix back button behavior and page jumping

src/encoded/static/components/errors.js
This was a simple misspelling of the HTML entities.
=> ENCD-4326 Fix HTML entities for quotes

src/encoded/static/components/filegallery.js, src/encoded/static/components/globals.js, src/encoded/static/components/search.js, src/encoded/static/components/vis_defines.js, src/encoded/static/libs/bootstrap/panel.js, src/encoded/static/scss/encoded/modules/_panels.scss, src/encoded/tests/data/inserts/file.json, src/encoded/tests/features/test_trackhubs.py, src/encoded/types/shared_calculated_properties.py, src/encoded/vis_defines.py
This branch has both front end and back end changes, with the bulk being in the front end.
The back end changes do change the API for datasets in that the `visualize` property used to contain a dict with assemblies as keys, and each assembly was a dict with the browser names as keys and the corresponding URL as the value.
This changes in this branch so that each assembly is now an array of browser names because the URL processing now gets handled in the front end because the URLs can change depending on user selections.
=> ENCD-4325 Juicebox browser

.travis.yml, README.md, buildout.cfg, cloud-config-cluster.yml, cloud-config-no-es.yml, cloud-config.yml, docs/npm-packages.md, package-lock.json, package.json
Update node/npm to the latest LTS versions (currently node 10.15.0 and npm 6.4.1).
Everyone who gets this branch’s changes _must_ update their node installation to these (or similar major) versions to do a build. How to upgrade depends on how you have installed node. I had a very non-standard installation that took a fair amount of work to update. I’m hoping people with manually or brew-installed npm will have a more straightforward upgrade.
I also included documentation for maintaining package.json and package-lock.json. package-lock.json is a newer name to the old npm-shrinkwrap.json, but it seems much easier to maintain.
=> ENCD-3971 Update node npm to version 10

src/encoded/static/scss/bootstrap/_navbar.scss, src/encoded/static/scss/encoded/modules/_navbar.scss
Should fix two style bugs on mobile:
(1) the sub-categories under the main links are very difficult to read, the contrast is not high enough
(2) when you click on a menu link to see the sub-categories, it is not obvious that the menu is scrollable (I made the menu the full height to avoid this problem)
=> ENCD-4408 mobile menu readability

src/encoded/static/components/search.js
Terms that are numbers were interpreted by JS as numbers and when compared to strings, were not matching and returning false, even when they were selected as filters.
=> ENCD-4444 Highlight selected facet terms numbers

src/encoded/static/components/filegallery.js
The primary issue was that this new code put in for Juicebox couldn’t react to login changes. The difficulty is that because we only have `@ids` for related_files, and not all related_files would necessarily load depending on their status, you have to attempt to load them even if none would load, and just see what happens.
This change reacts to login status changes, and whether we had attempted to load related_files before or not. If we had not, we load them even without a login change.
=> ENCD-4445 Handle log-in changes for related files in file tables.

src/encoded/static/components/dataset.js, src/encoded/tests/data/inserts/experiment.json, src/encoded/tests/data/inserts/organism_development_series.json, src/encoded/tests/data/inserts/replicate.json, src/encoded/tests/test_batch_download.py
Series objects with life_stage value not present caused a rendering error.
Now tables will insert a null value for those cases.
This ticket also fixes another related error uncovered during debugging: headers were displayed for tables that did not exist (due to related datasets not being viewable).
=> ENCD-4217 Rendering error series objects

src/encoded/schemas/aggregate_series.json, src/encoded/schemas/experiment.json, src/encoded/schemas/matched_set.json, src/encoded/schemas/organism_development_series.json, src/encoded/schemas/reference_epigenome.json, src/encoded/schemas/replication_timing_series.json, src/encoded/schemas/treatment_concentration_series.json, src/encoded/schemas/treatment_time_series.json, src/encoded/static/components/search.js
Numerical facets are sorted in ascending order.
Date facets are sorted with most recent at the top.
Ranges of numbers are not sorted.
=> ENCD-4467 Numerical facets sorted by value not frequency

src/encoded/static/components/biosample.js
I now add the embedded `biosample_ontology.dbxrefs` string arrays to biosample.dbxrefs and display the combined result. I check for the existence of both arrays before using them, though they seem to always exist. They both exist in the schema as optional arrays though, so I’d prefer to check for their existence first.
A subsequent ticket will remove some dbxrefs we use for `biosample_ontology.dbxrefs` from some biosample objects, but that shouldn’t cause changes to the front end. We temporarily see duplicate dbxrefs on the biosample page with this change, but that situation should be temporary until the data get updated.
=> ENCD-4418 Add biosample_ontology dbxrefs to biosample page

src/encoded/tests/test_types_file.py, src/encoded/types/file.py
Make file object point to upload bucket if upload credentials are regenerated.
=> ENCD-4487-reset-upload-bucket

src/encoded/tests/test_audit_file.py, src/encoded/types/file.py
Remove uploading from file statuses that get considered by incorrect file bucket audit.
=> ENCD-4500-remove-uploading-private-status-list

src/encoded/schemas/changelogs/genetic_modification.md, src/encoded/schemas/genetic_modification.json, src/encoded/tests/data/inserts/genetic_modification.json, src/encoded/tests/test_schema_genetic_modification.py
Changes were made to the GM schema in order to accommodate the STARR-seq and lentiMPRA assays.
Added new property introduced_elements for the group of elements to be characterized in both assays.
Added new category enum episome with introduced_elements dependency.
Changed dependencies to allow characterization to be specified without modified site.
=> ENCD-4464 add GM category enums

src/encoded/static/components/antibody.js, src/encoded/static/components/biosample.js, src/encoded/static/components/dataset.js, src/encoded/static/components/donor.js, src/encoded/static/components/experiment.js, src/encoded/static/components/file.js, src/encoded/static/components/item.js, src/encoded/static/components/objectutils.js, src/encoded/static/components/typeutils.js
* The biggest change is in the `Supersede` component of typeutils.js. I cleaned up the code to all be more consistent and easy to maintain. I also renamed `Supersede` to `ReplacementAccessions` to more accurately reflect its current role.
* I also modified a restricted-file display in the header of file pages so that it stops using CSS styles I removed in this ticket’s predecessor.
=> ENCD-4530 Fix duplicate alternate accessions

src/encoded/static/components/auditmatrix.js, src/encoded/static/components/search.js
We removed horizontal facets from the matrix page as part of the typeahead facet changes but forgot to also remove them from the audit matrix.
One other small change: the matrix pages had an empty "search-header-control" space which is now not created when not needed.
=> ENCD-4524 update audit matrix

src/encoded/types/dataset.py
Removed files.lab from line 514 as it was redundant
=> ENCD-4494-remove-duplicate-embedding

src/encoded/static/components/cart/add_multiple.js, src/encoded/static/components/cart/index.js, src/encoded/static/components/cart/search_controls.js, src/encoded/static/components/cart/toggle.js, src/encoded/static/components/dataset.js, src/encoded/static/scss/encoded/modules/_cart.scss, src/encoded/static/scss/encoded/modules/_facet.scss
Most changes are in cart/add_multiple.js. The existing `CartAddAll` component is for adding all search results to the cart, and got renamed to `CartAddAllSearch` to distinguish it from the new `CartAddAllElements` component which has the much simpler job of adding an array of dataset objects to the cart. It gets called from the “Add all items to cart” button that appears in any type of Series page.
=> ENCD-4414 Allow users to add exp to carts from series

src/encoded/static/components/genetic_modification.js
This branch branches off ENCD-4464-add-GM-category-enums which is QA Completed as I type this. Might need to clear up conflicts after that gets merged, but I’m not sure.
With this change, I now check for GM modification site property names in multiple places, so I moved existing code to a function and module-level variable so they can be shared.
=> ENCD-4517 Add UI for GM introduced elements

src/encoded/tests/test_types_donor.py, src/encoded/types/donor.py
The code that calculates the children property was instead calculating the parents themselves. 
I fixed it in src/encoded/types/donor.py so that children are calculated properly and added a file (src/encoded/tests/test_types_donor.py) with a test to make sure the children are indeed calculated and placed in the children property of the specified parents.
=> ENCD-4510 Fix human donor children calc prop

src/encoded/types/base.py
This should prevent KeyError when using set_status to go from content error/upload failed to uploading.
=> ENCD-4543-fix-status-hierarchy

src/encoded/static/components/__tests__/cart-test.js, src/encoded/static/components/cart/cart.js, src/encoded/static/components/cart/clear.js, src/encoded/static/components/cart/manager.js, src/encoded/static/components/cart/status.js, src/encoded/static/scss/encoded/modules/_cart.scss, src/encoded/static/scss/encoded/modules/_navbar.scss, src/encoded/tests/features/cart.feature
The most significant change is the refactorization of `CartClear`, which used to handle the trigger button as well as the modal it triggered. The modal now gets rendered by the new `CartClearModal` component so that both a now-separate button (now called `CartClearButton`) as well as the new menu item can trigger the Clear Cart warning modal.
Because “Clear Cart” would be the third item in the cart menu needing the current cart name, and because we now have a non-selectable menu item in the “Data” menu (“Collections”), now seemed the time to have a non-selectable menu item displaying the current cart name in the cart menu so I could remove them from each of “View cart,” “Share cart,” and “Clear cart.” I implemented this using a `<span>` within the menu `<li>`, so I had to add the `<span>` …
=> ENCD-4412 Add Clear Cart item to cart menu

src/encoded/schemas/antibody_lot.json
We are adding "targets.label" as a typeahead facet on search and report pages for type=AntibodyLot. It is placed right below the current "Target of antibody" and is titled "Target of antibody" itself. Re-naming the current "Target of antibody" to be "Target category" is in another ticket in this sprint.
=> ENCD-4564 add target typeahead to AntibodyLot pages

src/encoded/static/components/search.js
Two bug fixes here:
(1) When user types in a typeahead, and then chooses another facet, the typeahead facet terms should update according to the new filter (previously they did not). This is accomplished by moving the filtering into the render() function and by only keeping the search term, not the full filtered list, in state.
(2) Previously typeahead search bars would show or not show depending on how many terms were available and this introduced bugs (confusing behavior) if you searched on them and then selected/deselected other filters, because searches could be in state but not displayed. Now we will show the search bars for all typeaheads no matter how many terms there are.
=> ENCD-4560 update typeaheads after selections

src/encoded/static/components/objectutils.js
Collections pages display a collections logo. In the case where someone attempts to search for a collections page that does not exist, we have a fallback image. This fallback image was not getting displayed on some browsers. The new "ImageWithFallback" component fixes this issue by ensuring that the onError function is loaded.
=> ENCD-4548 fix fallback images on collection pages

src/encoded/static/components/genetic_modification.js
The table of biosamples that a particular GM references used to use the submitter-set biosample property `genetic_modifications`. This property still exists but a newer calculated property, `applied_modifications`, now references GMs that modify the biosample. GM pages did a GET request searching for biosamples that are modified by the GM using `genetic_modifications`, but this no longer returned anything. This branch now uses `applied_modifications` in this search.
Note that Donor objects still use `genetic_modifications` and this has not changed. `applied_modifications` is a property of biosamples only.
=> ENCD-4542 Display biosample table on GM pages

src/encoded/static/components/search.js
Back slashes entered in the typeahead search bars cause console errors. In order to prevent this, we will remove back slashes from search terms. We will also remove forward slashes for consistency handling slashes.
=> ENCD-4565 remove back slashes from search terms

cloud-config-cluster.yml, cloud-config-elasticsearch.yml, cloud-config-no-es.yml, cloud-config.yml
Temporary change that downloads java 8 211 from our aws prod s3 bucket and manually installs. Java 8 is behind a user login and we need to update to java 11, since 9/10 are not major releases.
=> ENCD-4581 Temp install java 8 through aws

src/encoded/static/components/filegallery.js
Removed the `setFilters` method because while debugging this, I found it made things _more_ confusing. This component has other one-line methods that I think _do_ help readability, but this one hurt it.
Most of this ticket is in the new method, `resetCurrentBrowser`, which changes the `currentBrowser` state when the chosen one becomes unavailable.
=> ENCD-4545 Update visualization browser list

src/encoded/schemas/analysis_step.json, src/encoded/schemas/changelogs/analysis_step.md, src/encoded/tests/data/inserts/analysis_step.json
Added 'long-read sequencing error correction' to the list of enums for analysis_step_types for AnalysisStep objects.
=> ENCD-4606 Add error correction step type

src/encoded/tests/data/inserts/experiment.json
From ENCD-4558, a merge conflict wasn't handled correctly. This fixes it by adding back a required property to an insert.
=> ENCD-4619 add experiment_classification to data insert

src/encoded/batch_download.py, src/encoded/static/components/cart/cart.js, src/encoded/static/scss/encoded/modules/_cart.scss, src/encoded/tests/features/cart.feature, src/encoded/tests/test_batch_download.py
The most memory-impactful change involves collecting all file objects from the experiment search results for all experiments in the cart. Before this branch, I do the same search but throw out the file information. Because I handle the facet selection manually in this branch, I have to track all files so I know which to include and exclude. These aren’t complete file objects — just the five properties we facet. But in extreme cases, this can include close to 400,000 of these small file objects.
=> ENCD-4541 Add multiple facets to cart view pages

src/encoded/batch_download.py, src/encoded/tests/test_batch_download.py
Adds s3_uri to metadata and tests header fields and actual report generated from ES.
=> ENCD-4657-add-s3-uri-to-metadata

src/encoded/static/components/matrix.js, src/encoded/static/scss/encoded/modules/_matrix.scss
* Many of the deletions in matrix.scss happened because I removed the dynamic shading when you scroll the matrix sideways. I mentioned in the meeting how this shading causes a re-rendering delay when scrolling from an edge with a very large matrix because the entire matrix re-renders when you add or remove shading through CSS class injection in Javascript.
* Most of the additions in matrix.scss make the various left-most column cells sticky.
* The one change to `convertExperimentToDataTable` splits the spacer rows to have one left-column cell and one cell that fills the rest of the row, so these rows now behave like the other rows with a sticky left cell. Spacer rows either have an expander button or no content.
=> ENCD-4586 Freeze left column of matrix

.travis.yml, pytest.ini, src/encoded/tests/features/forms.feature, src/encoded/tests/features/page.feature
Mostly adding longer delays to common problem areas. Earlier changes to Travis delay mechanisms didn’t seem to help. Successful BDD tests now take 30 minutes. Also includes an attempt to fix the “test failed, but when we reran the test to collect info, it passed” kinds of failures. Will only know if this fix helps as we move forward.
=> ENCD-4656 Fix BDD Travis CI test failures

src/encoded/schemas/file.json, src/encoded/tests/test_schema_file.py
Fixed the dependency making read_name_details available only if file_format = fastq.
=> ENCD-4062 Fix read name details dependency

src/encoded/static/scss/encoded/modules/_matrix.scss
Safari requires a browser prefix for position:sticky. Also a couple other small adjustments to fix small Safari-specific rendering issues. Those fixes do not affect other browsers.
=> ENCD-4704 Fix frozen column for Safari

src/encoded/static/components/filegallery.js
FileTable can be called from FileGalleryRenderer for experiments and annotations, but it can also be called from DatasetFiles where visualizations aren’t relevant to objects using DatasetFiles so it passes nothing for the required browserOptions.browserFileSelectHandler, and it fails prop validation. This change removes this property as a _requirement_, and checks whether it exists, and hides the Visualize column from the table if it doesn’t.
=> ENCD-4699 Fix Javascript crash display series file tables

src/encoded/static/components/filegallery.js
Graphs are only being displayed for 'released', 'in progress', or 'archived' files but graphs should be displayed for other files as well (depending on permissions, and if "include deprecated files" is checked).
=> ENCD-4770 Only filter revoked files when needed

src/encoded/static/components/genome_browser.js
If you navigate to the genome browser for mm10 and search for a gene, the chromosome start location is correct but the chromosome end location is incorrect. The end location appears to be a string concatenation rather than a computed location. (Oddly, there seems to be no issue for human gene look-ups.)
=> ENCD-4771 Gene locations for mouse incorrectly padded

src/encoded/static/components/genetic_modification.js
I was using this.context to get the login information, but should have been using this.props to get that. The effect was that this page always thought the user was logged out, preventing internal audits from displaying.
=> ENCD-4772 Fix context usage with GM object pages

src/encoded/static/components/objectutils.js, src/encoded/static/components/vis_defines.js, src/encoded/tests/features/test_trackhubs.py, src/encoded/vis_defines.py
Now that we have an embedded quick view browser (Valis), there is no need for a link to a browser in a new page.
=> ENCD-4791 remove Quick View

src/encoded/static/components/genome_browser.js, src/encoded/static/scss/encoded/modules/_genome_browser.scss, src/encoded/static/scss/encoded/modules/_panels.scss
This branch should fix 3 issues on IE 11:
(1) There should be no light gray background on the facet buttons (aside from the bars that show how many results there are).
(2) The tabs and their facets should not wrap except at narrow screen sizes.
(3) A message should be displayed on the genome browser tab on IE 11 suggesting that users upgrade their browsers because Valis does not support IE 11.
Coding note: I thought about putting the browser detection code in filegallery.js but I think it makes more sense in genome_browser.js because that is where the other error message is ("There are no visualizable results.") and because we still want to display the browser tab, we just don't want to display the browser in the tab.
=> ENCD-4773 fix browser styles on IE 11

src/encoded/static/components/filegallery.js
Right now mouse experiments with mm9 and mm10 files default to mm9. We want to default to the more recent assembly, so we should default to mm10.
=> ENCD-4775 default to mm10 over mm9

src/encoded/static/components/audit.js, src/encoded/static/components/experiment_series.js, src/encoded/static/components/filegallery.js, src/encoded/static/scss/encoded/modules/_audits.scss, src/encoded/static/scss/encoded/modules/_tables.scss, src/encoded/types/dataset.py
The functionality to display the highest audit level has moved out of a private function in filegallery.js into a new public React component in audit.js. That way this functionality could be shared with the ExperimentSeries table. But in the end we went another way, but moving this functionality out to a public place seems like the right thing to do, so I kept it here.
audit.js also got a new AuditCounts component that moves the display of audit icons and corresponding counts out of auditDecor.auditIndicators and into its own component, AuditCounts. This allows this display to be shared between the audit button and the ExperimentSeries table column for audits.
=> ENCD-4769 Add dataset properties on ExperimentPage

src/encoded/static/components/genome_browser.js
This branch fixes several issues with the genome browser:
- The browser does not display for cases where the file list is filtered down to one result.
- We were not displaying all available DNA and gene tracks.
- We renamed the genome and gene tracks:
--  genome track should be "GRCh38" or "mm10" etc
-- genes should be "GENCODE V29" for GRCh38 and hg19 and should be "GENCODE M21" on mm10
=> ENCD-4779 fix default tracks

src/encoded/static/components/audit.js
New component to display these audits used "null" to suppress display, but unfortunately I set the default value of null. Change the default to "undefined" so that the component would get the needed data from the passed object.
Planned for production hot fix.
=> ENCD-4817 Restore file table audit column

src/encoded/static/components/search.js, src/encoded/static/scss/encoded/modules/_search.scss
Caused by a needless extra div between "search-results" and `FacetList`.
=> ENCD-4828 Make facet box height same as results table

src/encoded/static/scss/encoded/modules/_genome_browser.scss
This branch should remove an empty border around the "done" div and also remove unnecessary margin at the top of the dropdown containing gene lookup results.
=> ENCD-4832 remove border on empty results

buildout.cfg, src/encoded/docs/updating_ontologies.md
Updating the ontology.json with the following releases:
- Uberon and CL: 2019-06-27
- EFO: 2019-09-16
- OBI: 2019-08-06
=> ENCD-4820-update-ontology

src/encoded/static/components/filegallery.js
Was using an obsolete CSS class for Raw Data table column headers.
=> ENCD-4846 Fix microRNA raw data table headers

src/encoded/static/scss/encoded/_base.scss
Use background-color regardless of what button/link is being disabled, instead of opacity.
=> ENCD-4880 Restore disabled button styling on certain buttons

src/encoded/static/components/region_search.js, src/encoded/static/components/search.js, src/encoded/static/components/vis_defines.js
Same as ENCD-4891-region-crash branch but with a `results.coordinates` processor to generate a “chr1:012345678-012345678” string to add to region search visualization URLs for UCSC. Adds that processing to `BrowserSelector` and changes `ucscUrlGenerator` to use that string.
=> ENCD-4891 Region search crash fix plus position

src/encoded/static/components/sorttable.js
From the ticket:
The comment in sorttable.js for the "display" property ends with “If `display` is specified, the following `getValue` doesn't get called.” This is true for displaying the value, but it’s misleading in that `getValue` still gets called for sorting the values.
=> ENCD-4866 fix sorttable comment

src/encoded/static/components/audit.js
ENCD-4692 introduced a new way to embed links in audit detail text. Before this, we had an unreliable and inflexible method of looking for /text/text/ strings in audit detail text and converting those to links. Now, links within the text are a kind of mini-variant of markdown that looks like {link text|link URI}.
To let us gradually convert over, I temporarily had the new audit details parser look for both the old and new patterns. With ENCD-4753, all audit details use the new pattern, so the Javascript to parse the old pattern is no longer needed. This branch removes that code.
=> ENCD-4863 Remove JS code to process paths in audit descriptions

src/encoded/static/components/filegallery.js
I redid Raw Data table border drawing so that it doesn’t work like Raw Sequencing Data table border drawing, because I had wrongly assumed before that they’re basically the same.
While Raw _Sequencing_ Data tables can have multiple pairs that share a replicate/library combination, and therefore should have bold lines between the pairs, Raw Data tables can’t have multiple groups that share a replicate/library combination — the groups are _defined_ by a shared replicate/library. Therefore, you can’t have a bold line that only underlines a group of files; the bold line has to separate groups and should therefore span the entire row.
So you’ll now see the bold line between groups spanning the entire row, and never see a bold line between files, as you can see in Raw Sequencing Data tables. …
=> ENCD-4858 Remove bolded line below certain raw data tables

src/encoded/tests/test_file_download.py, src/encoded/types/file.py
This redirects all file downloads instead of sending byte range requests through _proxy endpoint.
=> ENCD-4901-redirect-file-downloads

src/encoded/static/components/auditmatrix.js, src/encoded/static/components/matrix.js, src/encoded/static/components/objectutils.js, src/encoded/static/components/search.js, src/encoded/static/components/summary.js, src/encoded/static/scss/encoded/modules/_matrix.scss, src/encoded/static/scss/encoded/modules/_search.scss
I rearranged the matrix views (experiment and audit) so that all views that include facets follow a pattern of a wrapper div with display:flex, and then exactly two child divs: one with the facets taking up a horizontal portion and one with the main content of the page taking the rest. The matrix views now split the search terms input field off from the facets, and the view buttons off the main matrix view, and combines them both into the header div. That leaves just the facets and header content to share horizontal space, matching other pages that have facets.
The cart view display does have facets, and does follow this pattern, but uses different CSS classes and values for a different look, so it doesn’t _quite_ follow the pattern of the others.
I moved `<MatrixInternalTags>` from …
=> ENCD-4855 Extra-wide search facets

src/encoded/schemas/experiment.json, src/encoded/static/components/award.js
* The main part of this involves using `date_released` as a data source instead of the now-defunct `month_released` so that we don’t always display no data for experiment releases.
* I also removed the second parameter from dayjs() because that’s not supported unless you use the CustomParseFormat plugin, which we don’t include right now. dayjs() seems fine interpreting our dates without that.
* I removed the adjustment to date-submitted data because that often drives those numbers negative — we often release experiments submitted before the start date of a summary search, causing this to look like we’ve released more experiments than have been submitted. Now both released and submitted experiments accumulate over time with no adjustments.
=> ENCD-4816 Summary release date source change

src/encoded/static/components/app.js
Rearranging the drop-down menu to include link to functional characterization experiments. (Note: link should be https://www.encodeproject.org/search/?type=FunctionalCharacterizationExperiment without status=released because no experiments are released at this time).
Top section should be:
"Experiment matrix"
"Experiment search"
"Functional characterization search"
And "Summary" should be entirely removed.
=> ENCD-4885 add entry for functional characterization assays

src/encoded/static/components/region_search.js
An extra call to "navigate" was reversing user updates to a region search. A new search would load new results correctly and then revert to an original search (incorrectly). This update prevents the page from reverting to an original search.
=> ENCD-4892 region search refresh

src/encoded/static/components/schema.js
Currently the "oneOf" property in the target schema is an expandable button with an empty expandable section: https://www.encodeproject.org/profiles/target. We will omit the "oneOf" property from this section.
=> ENCD-4944 remove oneOf from target schema

src/encoded/static/components/filegallery.js, src/encoded/static/components/vis_defines.js
I added a mapping of browser name from the back end to a display name. This mostly maps from something to the exact same thing, but allows us to add new mappings in the future.
Indexed demo: ~https://encd-4848-juicebox-name-57715a626-fytanaka.demo.encodedcc.org/~
=> ENCD-4848 Display Juicebox for hic visualizations

src/encoded/audit/file.py, src/encoded/tests/test_audit_file.py
in file.py,  "def audit_file_matching_md5sum(value, system):" the AuditFailure categories were changed to all lower case to match other AuditFailure(s):
'Incorrect matching_md5sum' was changed to 'incorrect matching_md5sum'
'Matching md5 sums' was changed to 'matching md5 sums'
=> ENCD-4912-update-matching-md5-audit

cloud-config/config-build-files/cc-parts/CC_RUNCMD_DEMO.yml, cloud-config/config-build-files/cc-parts/CC_RUNCMD_ES.yml, cloud-config/config-build-files/cc-parts/CC_RUNCMD_FRONTEND.yml, cloud-config/deploy-run-scripts/a2en-run.sh, cloud-config/deploy-run-scripts/conf-apache/encoded.conf, cloud-config/deploy-run-scripts/conf-apache/some-vars.conf, cloud-config/deploy-run-scripts/conf-apache/the-rest.conf, cloud-config/deploy-run-scripts/conf-es/es-cluster-elect.yml, cloud-config/deploy-run-scripts/encd-install.sh, src/encoded/commands/deploy.py, src/encoded/memlimit.py
A bunch of isolated backend changes.  Some are not really testable(4908/4939) so as long as the machine doesn't fall over on deployment or usage.  We'll want to load test this and check logs(4938) . QA machine should be a cluster so we can add a new node(4937).  QA Cluster should be deployed from a fake tag(4947).  4911 can be tested directly by bonita/idan as with v91x0.
4947: Deployment bug fix that only impact bin/deploy where -b arg is a tag.
4911:  Makes upload limit 5gb.  This was already running in v91x0-test and v91x0 prod.
4937: Rare occasion we'll need to add one node to an already existing cluster.  This was used to add a new node to v91x0.
4938: There should be a new log /var/log/apache/forensic_log.log.  And a key in the current access.log to reference the incoming request in …
=> ENCD-4958 Group PR of 5 backend changes

src/encoded/static/components/matrix_reference_epigenome.js
This involved adding a non-breaking space to the relevant cells. Because the colors and striped SVG backgrounds are absolutely positioned, this has no visual effect otherwise. Without the non-breaking space, the height of the colored cells is zero on IE11.
=> ENCD-4970 Make reference-epignome cells render on IE11

.eslintrc.js, buildout.cfg, package-lock.json, package.json, src/encoded/search_views.py, src/encoded/static/components/app.js, src/encoded/static/components/index.js, src/encoded/static/components/matrix.js, src/encoded/static/components/matrix_audit.js, src/encoded/static/components/matrix_entex.js, src/encoded/static/components/matrix_experiment.js, src/encoded/static/components/matrix_reference_epigenome.js, src/encoded/static/scss/encoded/modules/_matrix.scss, src/encoded/tests/data/inserts/biosample.json, src/encoded/tests/data/inserts/experiment.json, src/encoded/tests/data/inserts/human_donor.json, src/encoded/tests/data/inserts/library.json, src/encoded/tests/data/inserts/replicate.json, src/encoded/tests/features/biosamples.feature, src/encoded/tests/features/matrix_entex.feature, src/encoded/tests/features/test_matrix.py, src/encoded/tests/features/views.feature, src/encoded/tests/test_batch_download.py, src/encoded/tests/test_search_views.py, src/encoded/types/experiment.py
* The SNO-126-allow-default-value-for-missing-aggregation-field branch that this branch relies on is merged into snovault dev, but it’s not yet tagged for release so buildout.cfg still points to this branch, whatever that means for merging this branch to dev.
* The new local test data allows for _one_ cell to display in the ENTEx matrix. This also caused changes in the counts for some BDD and non-BDD tests. See bottom note for a warning about this.
* Changes to package.json, package-lock.json, and .eslintrc.js are for a new ESLint verifier for React hooks.
* Using React hooks in MatrixPresentation to handle the flashing arrow state (no expandable sections with this matrix, so the flashing arrow state is the only state on this page). I commented the code liberally because none of us know …
=> ENCD-4222 Implement ENTEx matrix

src/encoded/static/scss/encoded/modules/_matrix.scss
Fix shading on header columns in IE11. (Also works on other browsers!)
=> ENCD-4996-fix-IE-shading

src/encoded/static/components/app.js, src/encoded/static/components/home.js, src/encoded/static/scss/encoded/modules/_home.scss
A number of changes here:
(1) Navigation links and SCREEN link point to screen.wenglab.org instead of screen.encodeproject.org. (They did redirect but this is better.)
(2) Suggestion url on homepage is updated.
(3) Unused `submitScreenSearch` is removed.
(4) Button links are updated and a button for GRCh38 is added.
=> ENCD-5001-SCREEN-updates

src/encoded/static/scss/encoded/modules/_home.scss
The Chrome v79 bug seems to involve not scaling absolutely positioned SVGs. To fix this I’ve made the svg a regular DOM element, but made the image behind it absolutely positioned. This works on Safari, Firefox, and Edge as well, though it breaks IE11. To fix that, I’m using the "uaTrident" CSS class so I can use the older CSS styles for IE11, where the SVG is absolutely positioned and the image is normal.
PR demo: https://encd-5007-home-svg-pr1-fytanaka.demo.encodedcc.org/
Not indexed as I type this, but it doesn’t need to be.
=> ENCD-5007 Home page SVG alignment in Chrome

src/encoded/tests/features/advanced_query_search.feature
Changed test to test "date_submitted" query in order to circumvent year roll-over problem.
=> ENCD-5023 fix advanced query search BDD test

src/encoded/static/components/filegallery.js, src/encoded/static/components/genome_browser.js
Three updates for this ticket:
(1) we do not display "Replicates" facet for Annotations
(2) we do not include files with unspecified replicates in "Replicates" facet for non-Annotations
(3) we do not display "rep" on the browser track labels for files with unspecified replicates
=> ENCD-4790 replicates in Valis

src/encoded/audit/experiment.py
added audit check for insufficient read length under the miRNA standards
=> ENCD-5010-Reduce-min-read-length-miRNA

src/encoded/schemas/changelogs/functional_characterization_experiment.md, src/encoded/schemas/functional_characterization_experiment.json, src/encoded/static/components/experiment.js, src/encoded/tests/test_schema_functional_characterization_experiment.py
2nd commit is adjustments to code in experiment.js to get the property to render, 3rd commit is reverting those changes. Visualization won't be included in this branch/ticket.
=> ENCD-5014-new-FCE-property-target-expression-percentile

src/encoded/static/components/experiment.js, src/encoded/tests/data/inserts/functional_characterization_experiment.json
The ticket also asked to display the minimum and maximum range, but the code to display them already exists. This just adds the expression percentile. Its value can potentially be zero, and should be displayed if it is.
=> ENCD-5053-display-target-expression-percentile

src/encoded/static/components/matrix.js, src/encoded/static/components/matrix_entex.js, src/encoded/static/components/matrix_reference_epigenome.js, src/encoded/static/scss/encoded/modules/_matrix.scss
* The issue with the Mars/Venus symbols was that Helvetica didn’t have those symbols defined so it fell back to a default font (not sure which) that has them shaped wrong. I now use Menlo which should appear on macOS, and Courier for Windows.
* matrixAssaySortOrder determines the sort order of the assays across the x-axis and was shared between the ENTEx and Reference Epignome matrices, but Idan wanted them to have their own sorting orders, so this array moved out of matrix.js and each matrix now has its own copy.
* The `legendText` properties of `entexDonors` might look odd, but I was surprised it still separates the digit from the unicode digits. I use letter-spacing to space them as the space I used to have between them had gotten very large with the new font.
* We have a new concept …
=> ENCD-5022-ENTEx-updates

package-lock.json, package.json
We've added an update to the Valis library which allows it to display a highlight location. This helps the user not lose track of the initial position of the browser. Currently this feature is not useful for Encode. However, we want Encode to point to the Valis update which enables this configuration.
=> ENCD-5037-valis-library-update

package-lock.json
This changes package-lock.json for ENCD-5037 _might_ have caused this crash. I haven't confirmed this yet, but I think updating Valis in package-lock.json and updating package-lock.json brought in — maybe — the wrong version of graphlib.
I’ll describe what I did for this Valis update to package-lock.json in the ticket.
=> ENCD-5088 graphlib crash fix
