src/encoded/audit/antibody_characterization.py
src/encoded/audit/biosample.py

Small changes to audit descriptions

2515 audit descriptions

---

src/encoded/static/components/__tests__/experiment-test.js
src/encoded/static/components/experiment.js
src/encoded/static/components/testdata/library/sid38806.js

I removed it in a bad merge. This puts it back.

2551 Put spikeins display back in place

---

src/encoded/static/components/item.js

This implements http://redmine.encodedcc.org/issues/2577

prompt to confirm removal of form fieldsets

---

src/encoded/schemas/analysis_step.json
src/encoded/schemas/pipeline.json
src/encoded/schemas/quality_metric.json
src/encoded/tests/data/inserts/quality_metric.json

#1400 fixes

---

src/encoded/audit/replicate.py
src/encoded/tests/test_audit_replicate.py

When the test of the audit is actually a negative case, things go much better.  I also touched another audit for platform that will hopefully be going away.  It was named file when it was a replicate audit.

2597 in progress replicates

---

src/encoded/schemas/quality_metric.json

#2512 qc objects

---

src/encoded/schemas/mixins.json
src/encoded/tests/data/inserts/fly_donor.json
src/encoded/tests/data/inserts/target.json
src/encoded/tests/data/inserts/worm_donor.json

#2592 add a link to target within genomic_alterations to capture mutated genes

2592 target genomic alterations

---

src/encoded/audit/antibody_characterization.py
src/encoded/audit/dataset.py
src/encoded/audit/experiment.py
src/encoded/audit/library.py

I am still waiting on Travis, but I thought I would get this in your queue.  It has been merged with Nikhils branch.

I hate extra yellow dots

---

src/encoded/audit/file.py
src/encoded/tests/test_audit_file.py

The tests ran locally.  They have not run here yet, but you may want to merge this as it is little

2605 matched replicate

---

src/encoded/schemas/mixins.json

Add "TMP/UV" to mutagen enum list.

#2592 - add enum "TMP/UV" to mutagen

---

src/encoded/audit/experiment.py

#2693 add audit to compare antibody_lot.host_organism in IP vs. control

Add audit for host_organism comparison

---

src/encoded/schemas/antibody_lot.json
src/encoded/schemas/biosample.json
src/encoded/schemas/dataset.json
src/encoded/schemas/donor.json
src/encoded/schemas/file.json
src/encoded/schemas/fly_donor.json
src/encoded/schemas/human_donor.json
src/encoded/schemas/library.json
src/encoded/schemas/mixins.json
src/encoded/schemas/mouse_donor.json
src/encoded/schemas/pipeline.json
src/encoded/schemas/worm_donor.json

#2637 added accessioned_status and preliminary and proposed status to donors

2637 status grouping

---

src/encoded/static/components/inputs/object.js

Fix the URI used to fetch objects for preview in forms.

2653 fix preview

---

src/encoded/static/components/dataset.js

This may be too many columns now...

Add a friendly file size to column to the files table.

---

src/encoded/audit/item.py
src/encoded/calculated.py
src/encoded/contentbase.py
src/encoded/loadxl.py
src/encoded/schemas/page.json
src/encoded/static/components/blocks/item.js
src/encoded/static/components/blocks/teaser.js
src/encoded/static/components/fetched.js
src/encoded/types/page.py

Enables embedding for page blocks and ensures referential integrity for links from subobjects.

Links for subobjects

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py

#2698 - Replacement audits and audit tests for branch #2693 which was merged but should be removed.

Add ENCODE3 ChIP control audits and tests

---

src/encoded/schemas/target.json

#2701 - Add "histone" and "other post-translational modification" as enums in target.investigated_as

Add new enums to target.investigated_as

---

src/encoded/static/components/__tests__/experiment-test.js
src/encoded/static/components/testdata/publication/PMID16395128.js
src/encoded/static/components/testdata/publication/PMID23000965.js

Removed just to make some progress. Returned it now with the new style of referrring to PMID references.

Return an experiment Jest test

---

src/encoded/commands/es_index_data.py

this fixes for the command
bin/es-index-data production.ini --app-name app

Fixed the "bin/es-index-data"

---

src/encoded/audit/experiment.py
src/encoded/audit/file.py

Updated which assays will require "possible controls" and "controlled_by"

2615 sh rna control

---

src/encoded/audit/experiment.py
src/encoded/schemas/library.json
src/encoded/tests/test_audit_experiment.py

this is the version that should work

2560 lib pair end 2

---

src/encoded/static/components/form.js
src/encoded/static/components/item.js
src/encoded/tests/features/forms.feature

This fixes 2756 (don't show schema_version on form) and 2758 (don't show a blank option for selects if there's a default)

more form bugs

---

src/encoded/schemas/mixins.json
src/encoded/static/mime.types

Doing a pull request for Esther

Add autosql as a MIME type for attachments

---

src/encoded/schemas/file.json
src/encoded/tests/data/inserts/file.json

Getting the field in there for forrest.  I still have other things to do with the audits for them to make sense now

2561 paired end to file

---

src/encoded/static/components/item.js

(should not validate starting_amount as string if it's a number)

fix loading biosample form

---

examples/submit_file.py
src/encoded/commands/check_files.py
src/encoded/schemas/file.json

#2785 add new file format enums and validate_map for #2763

Add wig and sam to file_format and validate_map

---

src/encoded/static/components/pipeline.js

Filter analysis step parents on the pipeline display so only parents belonging to the current pipeline display.

2791 pipeline update

---

src/encoded/static/components/blocks/fallback.js
src/encoded/static/components/blocks/richtext.js
src/encoded/static/components/blocks/search.js
src/encoded/static/components/blocks/teaser.js
src/encoded/static/components/layout.js

fixes issue 2795 (mostly regressions from the React 0.13 upgrade and the switch to loading react-forms in function scope)

fix a few bugs in the layout editor

---

src/encoded/schemas/biosample.json

Forgot the worm synch stage dependency

Add worm_synchronization_stage dependency

---

src/encoded/schemas/file.json

Add wig and sam to the file_format_extension mapping

Fix file.json for new file extensions

---

src/encoded/audit/experiment.py
src/encoded/schemas/library.json
src/encoded/tests/data/inserts/library.json
src/encoded/tests/test_audit_experiment.py
src/encoded/upgrade/library.py

Add fragmentation enum upgrades, changed tests and removed outdated ones

2768 new fragmentation enums

---

src/encoded/schemas/biosample.json
src/encoded/schemas/experiment.json
src/encoded/types/biosample.py
src/encoded/types/experiment.py

2789 rnai search

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py

2887 add dcc level audit

---

src/encoded/schemas/library.json
src/encoded/upgrade/library.py

Modified schema and upgrade as per #2768-6

Add sonication (generic microtip) enum to fragmentation_method

---

src/encoded/static/components/search.js

Fix a rendering error when search has no results

---

src/encoded/static/components/dataset.js

Raw file table now includes Validation Status, and Run Type and Read Length columns are now next to each other.
For 26rc3.

2760 Update experiment file table columns

---

src/encoded/upgrade/file.py

This will have a large affect on the numbers in the run_type facet

2539 change upgrade precedent

---

src/encoded/audit/file.py

This is failing travis, but we think that it is Travis not this one line.  We are restarting and I am making a pull request for Laurence so that he does not loose track of it.

2940 read length audit

---

.travis.yml

The .jar has been deprecated and will stop working in August.

Sauce connect 4

---

src/encoded/static/components/dataset.js

Reordered RAW file columns according to Cricket (and with Eurie’s agreement), and added a Lab column to the RAW file table.

2760 Experiment file table updates

---

src/encoded/schemas/file.json

#3010 - added new enum options to output_type

Add sex genome indexes to output_type

---

src/encoded/schemas/pipeline.json

In large merge I lost change of default from 1 to 2.  So the upgrades did not happen

Revert default schema value

---

src/encoded/schemas/experiment.json
src/encoded/schemas/pipeline.json
src/encoded/tests/data/inserts/analysis_step_run.json

Facet pipeline titles on pipeline searches, and files.pipeline.titles on experiment searches.

2977 Implement pipeline facets

---

src/encoded/static/components/pipeline.js

Removed version and accession from pipeline page main panel.

Change pipeline page panel

---

src/encoded/schemas/analysis_step.json
src/encoded/schemas/file.json

A few last minute enums.  Wouldn't be me if I didn't ask for more enums right before a release ;)

add encyclopedia enums and fix idr name

---

src/encoded/static/components/experiment.js
src/encoded/types/experiment.py

Was directly retrieving possible_controls with a calculated property rather than the usual search. Removed that calculated property and doing a normal search.

1448 Simplified possible_controls retrieval

---

src/encoded/schemas/antibody_characterization.json

#3083 added Aditi to list of reviewers for characterizations

Add Aditi as a reviewer

---

src/encoded/schemas/award.json
src/encoded/schemas/biosample.json
src/encoded/schemas/construct.json
src/encoded/schemas/rnai.json

Some small changes to boosted search - thanks Laurence!

2968 boost update

---

src/encoded/schemas/construct.json

#3066 - conditional dependency added based on construct_type for tags property. UI is broken though

3066 conditional construct tag

---

src/encoded/static/components/__tests__/antibody-test.js
src/encoded/static/components/antibody.js

3067 antibody links to all documents not just standards docs

---

src/encoded/static/components/app.js
src/encoded/static/components/footer.js
src/encoded/static/components/navbar.js
src/encoded/tests/features/toolbar.feature

3059 signin move to footer

---

src/encoded/persona.py
src/encoded/static/components/__tests__/store-test.js
src/encoded/static/components/app.js
src/encoded/static/components/form.js
src/encoded/static/components/index.js
src/encoded/static/components/lib/index.js
src/encoded/static/components/lib/store.js
src/encoded/static/components/mixins.js
src/encoded/static/components/navbar.js
src/encoded/static/components/user.js
src/encoded/tests/datafixtures.py
src/encoded/tests/features/conftest.py
src/encoded/tests/features/test_submitter_user.py
src/encoded/tests/features/user.feature
src/encoded/tests/test_access_key.py
src/encoded/tests/test_permissions.py
src/encoded/types/access_key.py
src/encoded/types/user.py

also includes:
- access keys and lab are now expanded in the user page view if user has view_details permission
- adds a link to the current user's profile in the user menu
- adds an impersonate-user view for use in tests and by admins

3037: add rudimentary user view including access key management

---

src/encoded/schemas/construct.json

Reverts ENCODE-DCC/encoded#865

Revert "3066 conditional construct tag"

---

development.ini
nginx-dev.conf
src/encoded/persona.py
src/encoded/static/components/app.js
src/encoded/static/components/collection.js
src/encoded/static/components/edit.js
src/encoded/static/components/errors.js
src/encoded/static/components/experiment.js
src/encoded/static/components/fetched.js
src/encoded/static/components/footer.js
src/encoded/static/components/form.js
src/encoded/static/components/home.js
src/encoded/static/components/item.js
src/encoded/static/components/mixins.js
src/encoded/static/components/navbar.js
src/encoded/static/components/pipeline.js
src/encoded/static/components/search.js
src/encoded/static/components/software.js
src/encoded/static/components/user.js
src/encoded/tests/test_access_key.py
src/encoded/tests/test_persona.py
src/encoded/types/user.py

This turned into a more significant refactor than initially envisaged...

Separate session properties #3074

---

src/encoded/schemas/biosample.json

#3139 - added two new enums to biosample.worm_life_stage

Add new worm life stages

---

src/encoded/commands/check_files.py

#3045 - added bedGraphs to validateFiles check

Add bedGraph validation

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py

Added exception in replication audit to single-cell isolation experiments, and added test called test_audit_experiment_single_cell_replicated

Exception for single-cell isolation experiments in replication audit

---

src/encoded/schemas/library.json
src/encoded/tests/data/inserts/library.json

Added dbxrefs to library.json (regex for GEO ids)

Adding dbxrefs in library

---

src/encoded/schemas/publication.json

Added an enum to categories in publication.json

did the thing

---

.travis.yml
src/contentbase/elasticsearch/indexer.py
versions.cfg

Stalled on travis-ci/travis-ci#4772, PR: travis-ci/travis-build#512.

Synced flush

---

src/encoded/batch_download.py
src/encoded/static/components/dataset.js
src/encoded/tests/data/inserts/file.json

Resolves 3200 and 3202.  I have a branch for 3199 that is branched off of this, but not sure it will get done by Mon/Tue.

3200 3202 replicates ui

---

src/encoded/audit/experiment.py

3146 audit fix

---

src/encoded/audit/biosample.py
src/encoded/tests/test_types_biosample.py
src/encoded/types/biosample.py

fixed the behavior of biosample sex, age calculated properties and
added a test that validates this behavior

changed sex and age and age_units in biosample calculated properties

---

src/encoded/static/components/app.js
src/encoded/static/components/navbar.js

3305 3300 about search fixes

---

docs/invalidation.rst
src/encoded/tests/data/inserts/file.json
src/encoded/visualization.py

Oh the browserness... also BONUS DOCS

3201 trackhub bioreps

---

src/encoded/audit/experiment.py
src/encoded/audit/replicate.py
src/encoded/tests/test_audit_replicate.py

cleaning up an audit to be more easily tested

moving biosample concordance to the replicate level

---

src/encoded/schemas/user.json
src/encoded/tests/test_permissions.py

Do I win the prize for test: code ratio?

3311 user permissions

---

src/encoded/schemas/chipseq_filter_quality_metric.json

3314 qc complexity descriptions

---

src/encoded/schemas/dataset.json

3343 dataset type enums

---

npm-shrinkwrap.json
package.json
src/encoded/search.py
src/encoded/static/components/app.js
src/encoded/static/components/index.js
src/encoded/static/components/matrix.js
src/encoded/static/components/mixins.js
src/encoded/static/components/search.js
src/encoded/static/scss/encoded/modules/_facet.scss
src/encoded/static/scss/encoded/modules/_tables.scss
src/encoded/static/scss/fontawesome/_icons.scss
src/encoded/tests/test_search.py
src/encoded/types/experiment.py

This is a work in progress; opening a pull request so @nikhilRP can review the search view (`matrix` function at the bottom of search.py)

(WIP) 3277 matrix

---

src/encoded/types/biosample.py

Changed age display to check and add synchronization time first

---

src/encoded/static/components/software.js

Removes circular dependency causing software.js modules to not load.

Remove pipeline dependency

---

src/encoded/static/components/app.js
src/encoded/static/components/search.js

@hitz doesn't want the matrix search linked yet. Ideally we probably want this change applied to v35 but not to master.

remove links to matrix search

---

src/encoded/static/components/dataset.js

Need to display project.project_type on summary panel of project datasets.

3211 Added project type

---

src/encoded/schemas/treatment_concentration_series.json
src/encoded/schemas/treatment_time_series.json

#3473 removed treatment_classification from treatment_time_series mixins

Remove treatment classification mixin

---

src/encoded/schemas/series.json

#3493 require listed experiments in related_datasets to be unique

Add uniqueItems restriction to related_datasets

---

src/encoded/schemas/file.json

#3492 Added new enums to assembly and genome_annotation for worm

Add support for ce11 assembly and WS235/WS245 annotations

---

src/encoded/static/components/form.js

Unfortunately we have to copy this whole component from react-forms just to add display of validation errors.

3499: display validation errors from list nodes in repeating fieldset component

---

src/encoded/schemas/target.json

#3487 add broad histone and narrow histone mark to enum list

Add broad and narrow mark enums

---

src/encoded/audit/antibody_characterization.py

#3475 - specify antibody characterization @id in audit message

3475 audit characterization

---

src/encoded/audit/biosample.py
src/encoded/audit/experiment.py
src/encoded/tests/test_audit_biosample.py
src/encoded/tests/test_audit_experiment.py

Branch that deals with 3482 and 3427 tickets.
1. Detect replicates without files
2. Detect biosamples with inconsistent "part_of" property in terms of biosample_term

3482 fileless replicates

---

src/encoded/audit/file.py
src/encoded/tests/data/inserts/file.json

#3476 - audit warnings for mismatched run_type and read length with controls

3476 file control audit

---

src/encoded/types/antibody_lot.py

#3529 fix antibody status bug for missing characterizations

3529 antibody fix2

---

src/encoded/schemas/antibody_characterization.json
src/encoded/schemas/antibody_lot.json
src/encoded/schemas/biosample.json
src/encoded/schemas/dataset.json
src/encoded/schemas/document.json
src/encoded/schemas/experiment.json
src/encoded/schemas/file.json
src/encoded/schemas/library.json
src/encoded/schemas/page.json
src/encoded/schemas/pipeline.json
src/encoded/schemas/publication.json
src/encoded/schemas/software.json
src/encoded/schemas/target.json

Remove `type` from definitions of facets and columns; it doesn't seem to be actually used anywhere.

[HOLD] remove unused facet and column types from schemas

---

src/encoded/static/components/app.js

Add link to acknowledgements page

---

src/encoded/schemas/matched_set.json
src/encoded/schemas/organism_development_series.json
src/encoded/schemas/replication_timing_series.json
src/encoded/schemas/treatment_concentration_series.json
src/encoded/schemas/treatment_time_series.json

Was only showing for ReferenceEpigenome before.

3520 Now showing targets in all dataset search results

---

src/encoded/schemas/file.json

#3600 Added restricted property boolean

Add restricted boolean to file

---

src/encoded/schemas/award.json

#3481 Added enums to project and rfa

3481 awards

---

src/encoded/schemas/chipseq_filter_quality_metric.json

Builds out and passes schema tests

Allow PBC2 to be "Infinity" or float

---

src/encoded/types/antibody_lot.py

#3588 Bug fix for display of cell types with status in lot_reviews

Fix for #3588 lot reviews

---

src/encoded/audit/antibody_characterization.py
src/encoded/audit/biosample.py
src/encoded/audit/experiment.py
src/encoded/audit/file.py
src/encoded/tests/test_audit_antibody_characterization.py
src/encoded/tests/test_audit_biosample.py
src/encoded/tests/test_audit_experiment.py
src/encoded/tests/test_audit_file.py

3605 - support Infinity
3586 - use ontology in part_of audit
3578 - duplicated NTR messages
3594 - spearman correlation STD fix

3586 3578 3594 3603

---

src/encoded/static/components/biosample.js
src/encoded/static/components/dataset.js
src/encoded/static/components/experiment.js
src/encoded/static/components/reference.js
src/encoded/static/components/software.js

Have stopped assuming all publication objects contain identifiers.

3637 References with missing identifiers

---

src/encoded/tests/test_views.py
src/encoded/types/antibody_approval.py

Avoid json-ld id clash with antibody_lot objects. Hide from non admin search results.

3656 Don't try to be too clever with old antibody_approval objects.

---

src/encoded/loadxl.py
src/encoded/schemas/cpg_correlation_quality_metric.json
src/encoded/tests/data/inserts/cpg_correlation_quality_metric.json
src/encoded/types/quality_metric.py

Added the tests/data/insert object, so maybe I got it right this time?

3635 wgbs rep corr qc metric

---

src/encoded/search.py
src/encoded/static/components/app.js
src/encoded/static/components/collection.js
src/encoded/static/components/index.js
src/encoded/static/components/matrix.js
src/encoded/static/components/report.js
src/encoded/static/components/search.js
src/encoded/static/scss/encoded/modules/_tables.scss
src/encoded/static/scss/fontawesome/_icons.scss

This adds the report view, and links to it from the search and matrix views. (It also exposes the matrix view of experiments by linking to it from the search and report views.)

report view

---

src/encoded/search.py

This fixes an issue noted in http://redmine.encodedcc.org/issues/3577#note-35

fix @id of report view

---

src/encoded/search.py
src/encoded/static/components/report.js

This fixes http://redmine.encodedcc.org/issues/3762

ignore report limit over 1000

---

src/encoded/static/components/biosample.js

…to biosample page document panels.

3714 Add treattment protocol documents

---

src/encoded/static/components/matrix.js
src/encoded/static/scss/encoded/modules/_facet.scss

This is a quick fix to stack all the facets vertically.

3738 - make matrix facets work better at mobile widths

---

Makefile
README.rst
setup.py
src/encoded/commands/deploy.py
versions.cfg

Reverts ENCODE-DCC/encoded#1196

Revert "3563 boto3"

---

setup.py
src/encoded/search.py
versions.cfg

2479 Support more expressive search queries.

---

src/encoded/static/components/dataset.js
src/encoded/static/components/experiment.js
src/encoded/static/components/sorttable.js

The graph filtering menu wasn’t always sorting correctly. Change the sorting algorithm to be more stable, and to use both the assembly and genome annotation in its sorting.

3680 Graph Filter Sorting

---

src/encoded/static/scss/encoded/modules/_tables.scss

Purely a CSS change to prevent these gaps from showing the checkerboard pattern where they should not be shown.

3815 report bg

---

src/encoded/static/components/dataset.js
src/encoded/types/file.py

3330 column update

---

src/encoded/audit/file.py

MAD changed to be DCC_ACTION

---

src/encoded/schemas/biosample.json

#3856 - added missing titles for biosample report view

Add title to biosample depleted_in

---

buildout.cfg
src/encoded/commands/generate_ontology.py

New ontology file was uploaded to S3

3831 assay rename

---

src/encoded/schemas/biosample_characterization.json

#3922 - added new method enums to biosample_characterization.json

3922 bio characterization methods

---

encode-proxy-nginx.conf

This is just a new sample file for nginx proxy.

ftp server nginix mod

---

src/encoded/schemas/file.json

Builds, runs, and passes local schema tests.
https://3532-mm10-minimal-8ba41b3-jseth.demo.encodedcc.org/

Add mm10-minimal to file assembly enum

---

src/encoded/static/components/dataset.js
src/encoded/static/scss/encoded/modules/_audits.scss

Display the validation status of each file in experiment file tables

3751 file validation status

---

src/encoded/static/components/matrix.js

Will figure out why the NavItem component didn’t work later. It was only to make the code more consistent and wasn’t supposed to make a functional change.

3969 Fix invariant violation error on matrix page

---

checkfiles/checkfiles.py
docs/invalidation.rst
src/encoded/search.py
src/encoded/static/components/region_search.js

This adjusts the matrix view to reuse the same logic for building filters as for the search view, rather than recreating it incompletely.

3997: fix matrix with != filters

---

src/encoded/static/components/app.js
src/encoded/static/components/search.js
src/encoded/static/scss/encoded/modules/_audits.scss

Make a subset of audit information visible while logged out.

4036 release the audits!

---

src/encoded/static/components/app.js
src/encoded/static/components/search.js
src/encoded/static/scss/encoded/modules/_audits.scss

Reverts ENCODE-DCC/encoded#1341

Revert "4036 release the audits!"

---

src/encoded/schemas/antibody_characterization.json

#3982 - new secondary characterization method enum

Add new secondary method and Jason as reviewer

---

src/encoded/types/antibody_lot.py

#4000 - fixed antibody status ranking comparison

4000 compliant over exempt

---

cloud-config.yml
docs/aws-deployment.rst

I have updated aws-deployment.rst file to reflect the procedure to update the crontab as a deployment step. No longer going to automate this step.
-Chris

4044 wal e crontab

---

src/encoded/search.py

Misnamed git branch.  This belongs with http://redmine.encodedcc.org/issues/4100

Minimal change to make mm10-minimal mimic mm10 for making trackHubs.

---

src/encoded/static/components/filegallery.js

Part of moving code around and adding a new module to avoid circular dependencies for annotations displaying file tables. Ended up with an old version of QcDetailsView component

4092 Fix merge error

---

.travis.yml

increase travis-ci timeout to 400s

---

src/encoded/schemas/experiment.json
src/encoded/tests/test_batch_download.py

#3882 Two target columns (label & gene) available in report view now

3882 target sort

---

src/encoded/static/components/browserfeat.js
src/encoded/static/components/graph.js

Handled by disabling the download button either until MS comes up with a way to do this, or until someone comes up with a means around this.

4041 Handle non-functional graph download button on MS Edge

---

src/encoded/search.py

Might still need some feedback, as I’m not sure this is the desired solution. See [this note](http://redmine.encodedcc.org/issues/3971#note-8) from the ticket for a description and rationalization.

3971 Blank page appears on report/?type=Dataset

---

.travis.yml

adding 
notifications:
slack: encode-dcc:UzhrrCRXvfpTd8bHAQ775aZw
for the travis ci slack notifications

4205 adding the travisCI reporting for slack

---

.travis.yml

Reverts ENCODE-DCC/encoded#1396

Revert "4205 adding the travisCI reporting for slack"

---

docs/advanced-search.rst
docs/aws-deployment.rst

Doc update

---

src/encoded/audit/file.py
src/encoded/tests/test_audit_file.py

changed erroneous into unexpected
mismatched into inconsistent

4211 RBNS assembly

---

scripts/LogToCsv.py

Created this script for parsing the encodproject.org.log to a more readable csv file when run.

adding log parser for encodcc logs

---

.travis.yml

i have resolved the conflicts with the .travis.yml file and have added the proper key encryption for use with slack.

4205 travis for slack

---

.travis.yml
README.rst
buildout.cfg
ez_setup.py
versions.cfg

To fix Python 2.7 Travis CI failure.

4250 Lock html5lib version

---

src/encoded/static/components/antibody.js
src/encoded/static/components/search.js

Let me know if I should add a status facet for antibodies and I’ll add that to this PR. That would be a very quick change.

3494 Antibody Status

---

src/encoded/schemas/file.json
src/encoded/tests/data/inserts/file.json

4308 nested tad

---

.travis.yml
README.rst
buildout.cfg
ez_setup.py
scripts/keyValidation.sh
src/encoded/schemas/annotation.json
src/encoded/schemas/experiment.json
src/encoded/schemas/file_set.json
src/encoded/schemas/fly_donor.json
src/encoded/schemas/human_donor.json
src/encoded/schemas/matched_set.json
src/encoded/schemas/mouse_donor.json
src/encoded/schemas/organism_development_series.json
src/encoded/schemas/project.json
src/encoded/schemas/publication_data.json
src/encoded/schemas/reference.json
src/encoded/schemas/reference_epigenome.json
src/encoded/schemas/replication_timing_series.json
src/encoded/schemas/series.json
src/encoded/schemas/treatment_concentration_series.json
src/encoded/schemas/treatment_time_series.json
src/encoded/schemas/ucsc_browser_composite.json
src/encoded/schemas/worm_donor.json
versions.cfg

The script i have added will verify the aws keys are valid for download and upload of a file to a s3 test bucket.

adding key verification script

---

scripts/keyValidation.sh

You can now select from prod or demo based on server location and correct keys.

added functionality to script to select from demo or prod

---

src/encoded/schemas/annotation.json
src/encoded/tests/data/inserts/annotation.json

Added long-range chromatin interactions to annotation.json

---

src/encoded/audit/dataset.py
src/encoded/audit/experiment.py

‘mismatched file status’ moved

moving audit from Experiment to Dataset level

---

src/encoded/audit/experiment.py

(1) missing spike-ins for RNA libraries
(2) missing possible controls for ChIP-seq

excluding GGR from certain audits

---

src/encoded/schemas/biosample.json

#3921 Make biosample.note import_items

Make biosample.note import_items

---

src/encoded/search.py
src/encoded/static/components/app.js
src/encoded/static/components/matrix.js
src/encoded/static/components/navigation.js
src/encoded/static/components/search.js
src/encoded/tests/features/search.feature
src/encoded/tests/features/title.feature

Reverts ENCODE-DCC/encoded#1481

Revert "4260: filter nav links and search to status=released by default when logged out"

---

src/encoded/audit/experiment.py

fixing double report on error in experiment audit of assay_term_name/id

fixing audit in experiment

---

buildout.cfg

new ontology.json

---

docs/aws-deployment.rst

Updated the deployment doc to scan for batch upgrade errors.

4468 batchupgrade release process

---

src/encoded/audit/experiment.py

#4445 - missed comma in assays with control list

Add missing comma

---

src/encoded/audit/pipeline.py
src/encoded/types/pipeline.py

Reverts ENCODE-DCC/encoded#1548

Revert "4423 audit pipelines"

---

src/encoded/audit/experiment.py

Reverts ENCODE-DCC/encoded#1553

Revert "4516 encode2 standards"

---

src/encoded/static/components/biosample.js

Don’t assume biosample.genetic_modifications exists — check first.

4556 Don’t assume biosample.genetic_modifications

---

src/encoded/static/components/filegallery.js

Does not hide empty “Mapping assembly” columns.

4546 raw assembly

---

src/encoded/schemas/file.json

4436 rbns logos

---

src/encoded/schemas/file.json
src/encoded/tests/test_file.py

Tested on demo and with pytest

4649 mapped run type

---

src/encoded/audit/experiment.py

#4579 - Fix links in construct audit message

Fix links in construct audit msg

---

src/encoded/static/components/biosample.js

Simply add the same submitter_comment display from experiments to biosamples.

4408 Display submitter common on biosamples

---

src/encoded/static/components/report.js

The back end already has done enough to make the menu titles appear. But the front end had a bug that prevented this from working. It now simulates the schema columns better when schema columns don't exit.

4667 missing columns

---

cloud-config-cluster.yml
cloud-config-elasticsearch.yml

Now clusters made with the elasticsearch cloud config, report memory stats to cloud watch. An AWS IAM rule was also applied to allow connections. This has been tested and I was able to make a dashboard with the stats.

4560 aws mem tool

---

cloud-config-cluster.yml
cloud-config-elasticsearch.yml
cloud-config.yml

4028 unattended upgrades

---

src/encoded/schemas/file.json

#4737 - add pseudoreplicate idr thresholded peaks to output_type

Add pseudoreplicated idr thresholded peaks in output_type

---

src/encoded/schemas/software.json

#4725 - add ATAC-seq and ChIA-PET as enums in software.purpose

Add new purpose enums

---

src/encoded/static/components/genetic_modification.js

Was using regular 'context' instead of 'results'. I closed the last PR because I thought there was a problem, but it’s OK. Just resubmitting the same branch again.

4753 Genetic modification search results result in a Javascript crash

---

src/encoded/audit/experiment.py
src/encoded/audit/file.py

4751 roadmap

---

src/encoded/static/components/biosample.js
src/encoded/static/components/experiment.js
src/encoded/static/components/genetic_modification.js
src/encoded/static/components/objectutils.js
src/encoded/static/scss/encoded/modules/_genetic_modification.scss
src/encoded/static/scss/encoded/modules/_panels.scss

Mostly just a matter of shuffling existing code around to reorder. Also added just a touch of AirBnB compliance to genetic_modifcation.js, but not all-out.

4688 Location of "genetic modifications" in pages is off

---

cloud-config-cluster.yml
cloud-config-elasticsearch.yml
cloud-config.yml

Allows emails to be sent from external DNS.

updated to allow non internal DNS for email

---

etc/encoded-apache.conf

Allows users to log in to the site, BUT will still block POST/PATCH/PUT.

4695 block post expt login

---

src/encoded/schemas/human_donor.json
src/encoded/static/components/biosample.js
src/encoded/static/components/dbxref.js
src/encoded/static/components/globals.js
src/encoded/static/components/platform.js
src/encoded/static/components/target.js

Primary changes:
* HumanDonor schema changed to allow “NIH:” as a Dbxref.
* Dbxref array changed to process NIH: dbxrefs as links.
Collateral changes:
* Donor functions changed to not accept a panel title from the caller.
* Changed Donor function to just display their own title. Not sure why I had parameterized that long ago.
* Made dbxrefs.js AirBnB compliant because it’s easy on that file.

3180 nih donor dbxrefs

---

src/encoded/static/components/filegallery.js

Because I had merged Esther’s 1384-whitespace-upgrades branch into my 4766-raw-file-crash branch, I had lots of changes not relevant to this ticket. So I created a new branch off master and just took my changes from 4766-raw-file-crash and put them in here.

4766 Re-apply my changes from 4766-raw-file-crash

---

src/encoded/static/components/dataset.js
src/encoded/static/components/experiment.js
src/encoded/static/components/typeutils.js

Also fixed an issue where the Award label could appear with no value.

4651 Remove link from dataset references to award

---

src/encoded/visualization.py

If request.host_url is localhost, trackhub metadata backlinks will go to production.

3817 trackhub cache spa

---

src/encoded/schemas/bigwigcorrelate_quality_metric.json
src/encoded/schemas/bismark_quality_metric.json
src/encoded/schemas/chipseq_filter_quality_metric.json
src/encoded/schemas/complexity_xcorr_quality_metric.json
src/encoded/schemas/correlation_quality_metric.json
src/encoded/schemas/cpg_correlation_quality_metric.json
src/encoded/schemas/duplicates_quality_metric.json
src/encoded/schemas/edwbamstats_quality_metric.json
src/encoded/schemas/edwcomparepeaks_quality_metric.json
src/encoded/schemas/encode2_chipseq_quality_metric.json
src/encoded/schemas/fastqc_quality_metric.json
src/encoded/schemas/filtering_quality_metric.json
src/encoded/schemas/generic_quality_metric.json
src/encoded/schemas/hotspot_quality_metric.json
src/encoded/schemas/idr_quality_metric.json
src/encoded/schemas/idr_summary_quality_metric.json
src/encoded/schemas/mad_quality_metric.json
src/encoded/schemas/quality_metric.json
src/encoded/schemas/samtools_flagstats_quality_metric.json
src/encoded/schemas/samtools_stats_quality_metric.json
src/encoded/schemas/star_quality_metric.json
src/encoded/schemas/trimming_quality_metric.json

test_load_workbook passes
test_load_schema passes

Add title property to qc metric objects

---

src/encoded/static/components/file.js

Just rearranging the output data, and adding output_type to the summary panel.

4882 output type

---

src/encoded/schemas/annotation.json

added methylation summary and variant calls to annotation_type

4857 annotation types

---

src/encoded/schemas/analysis_step_run.json
src/encoded/schemas/antibody_lot.json
src/encoded/schemas/biosample.json
src/encoded/schemas/characterization.json
src/encoded/schemas/construct.json
src/encoded/schemas/dataset.json
src/encoded/schemas/document.json
src/encoded/schemas/organism.json
src/encoded/schemas/pipeline.json
src/encoded/schemas/platform.json
src/encoded/schemas/source.json
src/encoded/schemas/talen.json

#3958 - Removed defaults in schema for required properties

3958 defaults

---

src/encoded/tests/test_types_antibody_lot.py
src/encoded/types/antibody_lot.py

#4513 - deals with not active primaries better but still not perfect

Deal with not active primaries better

---

src/encoded/static/components/file.js

I keep forgetting never to display file.accession — should always display file.title which takes external_accession into account.

4917 Stop using file.accession

---

src/encoded/static/components/antibody.js
src/encoded/static/components/award.js
src/encoded/static/components/biosample.js
src/encoded/static/components/dataset.js
src/encoded/static/components/doc.js
src/encoded/static/components/donor.js
src/encoded/static/components/experiment.js
src/encoded/static/components/file.js
src/encoded/static/components/filegallery.js
src/encoded/static/components/genetic_modification.js
src/encoded/static/components/index.js
src/encoded/static/components/pipeline.js
src/encoded/static/components/software.js
src/encoded/static/components/statuslabel.js
src/encoded/static/components/talen.js
src/encoded/static/scss/encoded/modules/_characterizations.scss

Most of this involved changing the Experiment component to check for and add the `internal_status` value to the StatusLabel component. I also updated the StatusLabel module to be AirBnB compliant, since it’s a small module. This also involved making it the default module from this file, so all modules that imported it had to be updated for this. Lastly, styles for the internal_status component had to be created to match the colors in the ticket.

4948 internal status display on experiment pages

---

src/encoded/schemas/fly_donor.json
src/encoded/schemas/worm_donor.json

#3220 fly_donor and worm_donor.organism are now import_only

Make organism import_items in fly and worm donors

---

src/encoded/static/scss/encoded/modules/_characterizations.scss

The new colors come from [Redmine #4948 note #11](http://redmine.encodedcc.org/issues/4948#note-11).

4948 internal_status badge color change

---

src/encoded/schemas/mouse_donor.json

#3220 made mouse_donor.organism import_only

Make mouse_donor.organism import_only too

---

src/encoded/static/components/region_search.js
src/encoded/static/components/search.js

The case of the `listing` function changed to satisfy AirBnB, and I missed that region-search still called it with the old case.

4988 region search crash

---

src/encoded/static/components/award.js

4856 Update award chart text

---

src/encoded/static/components/genome_browser.js
src/encoded/static/components/objectutils.js
src/encoded/static/components/search.js
src/encoded/static/scss/encoded/_theme.scss
src/encoded/static/vis_defs/ChIP_vis_def.json
src/encoded/static/vis_defs/HIST_vis_def.json
src/encoded/tests/features/test_trackhubs.py
src/encoded/types/dataset.py
src/encoded/visualization.py

* Tuned default biodalliance settings
* No "export" button
* Persisting location
* Archived files off by default
* Histone stable peaks labelling
* "Beta" feature only seen by logged in users
Demo: https://4533-biodalliance-bec301b-tdreszer.demo.encodedcc.org/

4533 qv gate

---

src/encoded/schemas/library.json

Adding enums to lists of:
1) library_size_selection_method 2) crosslinking_method

5030 library chia pet

---

src/encoded/schemas/library.json

Adding another enum to the list of fragmentation_method in library

adding sanitation enum to library

---

buildout.cfg

Might be worthwhile to check this with a local buildout, cd into develop/snovault and do a git status.

bump version

---

src/encoded/schemas/publication.json

#5131 new enum added to publication.published_by

Add historical reference published_by enum

---

src/encoded/schemas/donor.json
src/encoded/schemas/fly_donor.json
src/encoded/schemas/human_donor.json
src/encoded/schemas/mouse_donor.json
src/encoded/schemas/worm_donor.json

#5094 - Removed encode and roadmap-epigenomics from regex

5094 donor

---

src/encoded/schemas/antibody_characterization.json

ENCD-3388 (RM5201) Add Carrie to list of antibody reviewers
Added Carrie's user uuid to antibody_characterization.reviewed_by enum list

ENCD-3388 (RM5201) Add Carrie to list of antibody reviewers

---

src/encoded/schemas/file.json

Fixing file.json dependencies to allow submission of file with no status specified even if no_file_available is FALSE

ENCD-3413 file

---

src/encoded/upgrade/upgrade_data/analysis_step_5_to_6.py

ENCD-3237: Tighten analysis_step.name regex and add calcprop analysis_step_version.name
Added analysis_step upgrade for last minute ChromHMM steps that were added

ENCD-3237: Tighten analysis_step.name regex and add calcprop analysis_step_version.name

---

.travis.yml

add dist: precise (12.02)

---

src/encoded/static/components/sorttable.js

Not sure this is a great fix, but it does work and I understand why it works. What I don’t understand is why this is a problem in the first place. It seems to imply to me that React has a bug, but I don’t even know how to characterize it to put into a report. During debugging for this, I move two experiments — one that showed the problem and one that didn’t — closer and closer to each other in their characteristics, hoping one would either start showing the problem or one would stop showing it, but even though I had them basically identical, one still showed the problem and the other didn’t.
So let’s just go with this for now. Again, I understand how the fix completely prevents the problem. I just don’t know why doing things the normal way shows this problem in Safari and IE11.

ENCD-3459 safari hang

---

checkfiles/checkfiles.py
checkfiles/requirements.txt

ENCD 3466 bot

---

src/encoded/schemas/changelogs/file.md
src/encoded/schemas/file.json
src/encoded/upgrade/file.py

removing unknown run_type and mapped_run_type in file

ENCD-3347 removing unknown run_type and mapped_run_type in file

---

src/encoded/audit/biosample.py
src/encoded/audit/experiment.py
src/encoded/schemas/biosample.json
src/encoded/schemas/changelogs/biosample.md
src/encoded/schemas/changelogs/experiment.md
src/encoded/tests/datafixtures.py
src/encoded/tests/test_audit_biosample.py
src/encoded/tests/test_audit_experiment.py
src/encoded/tests/test_ontology_slims.py
src/encoded/tests/test_schema_biosample.py
src/encoded/tests/test_upgrade_biosample.py

adding biosample_term_name to required properties of bio sample and simplifying audit code. changelings were updated to reflect new required and effectively required properties in bio sample and experiment

ENCD 3194 fix

---

buildout.cfg
src/encoded/commands/generate_ontology.py
src/encoded/docs/updating_ontologies.md
src/encoded/schemas/award.json
src/encoded/schemas/mixins.json
src/encoded/schemas/pipeline.json
src/encoded/types/assay_data.py

ENCD 3477 new assays

---

src/encoded/static/components/pipeline.js

I changed the loops that draw the input/output file types so that they collect input file types for the current steps including those that _aren’t_ shared with a parent step. After all the shared file type nodes get drawn, all the remaining input file type nodes that aren’t shared with a parent’s output file type nodes then get drawn.

ENCD-3452 Reads not appearing on pipeline graphs

---

README.md

@hitz PR for adding java 8 dependency to readme along with troubleshooting instructions.

ENCD-3626 Add java 8 install dependency to README

---

src/encoded/schemas/antibody_characterization.json
src/encoded/schemas/biosample_characterization.json
src/encoded/schemas/changelogs/antibody_characterization.md
src/encoded/schemas/changelogs/biosample_characterization.md
src/encoded/schemas/changelogs/construct_characterization.md
src/encoded/schemas/changelogs/donor_characterization.md
src/encoded/schemas/changelogs/genetic_modification_characterization.md
src/encoded/schemas/changelogs/rnai_characterization.md
src/encoded/schemas/characterization.json
src/encoded/schemas/construct_characterization.json
src/encoded/schemas/donor.json
src/encoded/schemas/donor_characterization.json
src/encoded/schemas/file.json
src/encoded/schemas/fly_donor.json
src/encoded/schemas/genetic_modification.json
src/encoded/schemas/genetic_modification_characterization.json
src/encoded/schemas/human_donor.json
src/encoded/schemas/library.json
src/encoded/schemas/mouse_donor.json
src/encoded/schemas/pipeline.json
src/encoded/schemas/rnai_characterization.json
src/encoded/schemas/worm_donor.json
src/encoded/static/components/antibody.js
src/encoded/tests/data/inserts/antibody_characterization.json
src/encoded/tests/data/inserts/biosample_characterization.json
src/encoded/tests/data/inserts/mouse_donor.json
src/encoded/tests/test_types_antibody_lot.py
src/encoded/tests/test_upgrade_characterization.py
src/encoded/upgrade/antibody_characterization.py
src/encoded/upgrade/characterization.py

Many changes by others to add submitter_comments to various objects. My part was to add the submitter_comments display to antibody characterizations.

ENCD-3584 submitter comments

---

src/encoded/static/components/search.js

(so it also works from object picker)

ENCD-3655 Move file assemblies calculation into ResultTable

---

buildout.cfg
src/encoded/commands/generate_ontology.py
src/encoded/docs/updating_ontologies.md

Encd 3632 reshim methylations

---

src/encoded/types/experiment.py

remove 'mRNA '

---

src/encoded/docs/schema-changes.md

Encd 3647 schema docs

---

src/encoded/types/dataset.py
src/encoded/types/shared_calculated_properties.py
src/encoded/visualization.py

PR splitting of ENCD-3625 and ENCD-3659

ENCD-3625 Add missing visualization button

---

src/encoded/visualization.py

PR splitting ENCD-3625 and 3659

ENCD 3659 assemblies key not in result set items

---

src/encoded/schemas/human_donor.json

Schema change to bring back the lab facet.

ENCD-3581 Restore Lab facet

---

src/encoded/schemas/analysis_step.json

Added a facet for lab in the analysis_step.json schema.

ENCD-1972 Add status facet for analysis-step

---

src/encoded/visualization.py

replacement for #2098 .  The branch name was the same as the tag so I changed it.

[hotfix] ENCD-3736 Fix pop error

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py

1. excluding DNase from mixed run type audit
2. adding a test for that exclusion

ENCD-3699 Remove mixed run type audit from DNase

---

src/encoded/audit/experiment.py

we are removing an audot for NTR assay from experiment audits

ENCD-3760 Remove the NTR assay audit

---

src/encoded/audit/experiment.py

Resolving audit error bug (WGBS audit)

ENCD-3781 Resolve WGBS lambda audit error

---

src/encoded/audit/experiment.py

ENCD-3700 Remove unreplicated exp audit for genetic mod DNase

---

src/encoded/schemas/experiment.json
src/encoded/schemas/file.json
src/encoded/static/components/file.js
src/encoded/types/file.py

Adding platfrom embedding in file schema
Adding back the platform facet on experiment and file search pages

ENCD-3745 Add platform to file and exp facets

---

README.md

This PR contains
- ES5 instructions 
- Minor install dependency requirements

ENCD 3749: Update README for ES5 and dependency requirements

---

buildout.cfg

https://github.com/ENCODE-DCC/snovault/releases/tag/1.0.1

ENCD-3813-update-to-snovault-1.0.1

---

buildout.cfg

Fix while release v65 es5 round 2

Update to snovault 1.0.2

---

cloud-config-cluster.yml
cloud-config-elasticsearch.yml
cloud-config.yml
src/encoded/peak_indexer.py

Missing changes for max clause update

ENCD-3851 Add max clause es5 updates

---

versions.cfg

Split from ENCD-3815 fix test search  #2112

ENCD-3816 Update selenium version to 3.8.1

---

src/encoded/schemas/biosample.json
src/encoded/schemas/changelogs/biosample.md

* Added property **preservation_method** to biosample schema with enums _cryopreservation_ and _flash-freezing_
* Updated biosample changelog with non-schema incrementing change

ENCD-3819 Add biosample preservation method

---

buildout.cfg

1.0.3:
-SNO-8 Add JSONSchemas type to profiles page (#73)

ENCD-3865 Update to snovault version 1.0.3

---

README.md

first pr was merged to master and reverted.  This one will be merged to dev

ENCD-3827 Fix ES5 version in README

---

buildout.cfg

1.0.4
-SNO-15 Add index to storage propertysheet (#82)
-SNO-14 Update delete script (#82)

ENCD-3878 Update to snovault version 1.0.4

---

CHANGES.rst
setup.py

Update to version 66.0

---

src/encoded/schemas/biosample.json

Adding facet for presence/absence of NIC on biosample

ENCD-3893 Add NIH cert to biosample facets

---

src/encoded/schemas/genetic_modification.json
src/encoded/search.py

Makes GeneticModifications searchable from search box.

ENCD-3604 Update boost to include GM accessions

---

.travis.yml

I assigned this ticket to a sprint and release, but I don’t really know how those should be set for this.

ENCD-3915 Remove chromedriver lock from Travis

---

src/encoded/schemas/changelogs/file.md
src/encoded/schemas/file.json
src/encoded/tests/test_upgrade_file.py
src/encoded/upgrade/file.py

this is a fix of previously merged branch

[bug-fix] ENCD-3809 Fix failing batch upgrade

---

CHANGES.rst
setup.py

Release v67x1

---

src/encoded/audit/item.py
src/encoded/schemas/analysis_step_run.json
src/encoded/schemas/changelogs/analysis_step_run.md
src/encoded/tests/data/inserts/analysis_step_run.json
src/encoded/tests/datafixtures.py
src/encoded/tests/test_schema_analysis_step_run.py
src/encoded/tests/test_upgrade_analysis_step_run.py
src/encoded/types/pipeline.py
src/encoded/upgrade/analysis_step_run.py

This removes virtual as possible analysis_step_run status.

ENCD-3772-remove-virtual

---

src/encoded/audit/experiment.py
src/encoded/audit/item.py
src/encoded/schemas/changelogs/experiment.md
src/encoded/schemas/changelogs/reference.md
src/encoded/schemas/changelogs/treatment_time_series.md
src/encoded/schemas/dataset.json
src/encoded/schemas/experiment.json
src/encoded/schemas/reference.json
src/encoded/schemas/treatment_time_series.json
src/encoded/static/components/item.js
src/encoded/tests/test_audit_experiment.py
src/encoded/tests/test_permissions.py
src/encoded/tests/test_schema_experiment.py
src/encoded/tests/test_types_series.py
src/encoded/tests/test_upgrade_dataset.py
src/encoded/upgrade/dataset.py

Upgrades ready to review to submitted and adds import_items permission to status field.

ENCD-3780-remove-ready-for-review

---

src/encoded/batch_download.py

**Minor modification to format_row to strip out any tab spaces before sending it to the attachment**

ENCD-3645 & ENCD-3716 Strip white spaces from values

---

src/encoded/loadxl.py
src/encoded/schemas/aggregate_series.json
src/encoded/schemas/changelogs/aggregate_series.md
src/encoded/static/components/dataset.js
src/encoded/static/components/search.js
src/encoded/tests/data/inserts/aggregate_series.json
src/encoded/types/dataset.py

Adding aggregate series to support HiC mega-maps

ENCD-3938 Adding new Series type "AggregateSeries"

---

src/encoded/schemas/antibody_characterization.json
src/encoded/schemas/biosample.json
src/encoded/schemas/changelogs/annotation.md
src/encoded/schemas/changelogs/antibody_lot.md
src/encoded/schemas/changelogs/biosample.md
src/encoded/schemas/changelogs/experiment.md
src/encoded/schemas/experiment.json
src/encoded/schemas/mixins.json
src/encoded/static/components/app.js
src/encoded/tests/data/inserts/biosample.json
src/encoded/tests/test_types_biosample.py
src/encoded/types/biosample.py

new type was added to biosample, it required also chnaging the order of biosample summary - so it was changed too, and tests were updated

ENCD-3935 adding new biosample type "single cell"

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py
src/encoded/tests/test_audit_file.py

Re-writing the logic of chip-seq control read depth audit

ENCD-3739 rewriting chip control read depth audit

---

.gitignore
buildout.cfg
cloud-config-cluster.yml
cloud-config-elasticsearch.yml
cloud-config-no-es.yml
cloud-config.yml
ini-templates/base-template.ini
ini-templates/development-template.ini
ini-templates/production-template.ini
src/encoded/commands/deploy.py
src/encoded/region_indexer.py

This PR combines the follow PRs which have 1-1 match with encode tickets
#2227  - ENCD-3980
#2226  - ENCD-3621
#2211   - ENCD-3620(Tim region search updates)
#2180  - ENCD-3933

Deploy updates es and region

---

CHANGES.rst
setup.py

Reverts ENCODE-DCC/encoded#2230

Revert "Update to version 69.0"

---

src/encoded/static/components/app.js

See https://encodedcc.atlassian.net/browse/ENCD-3641 for my explanation of the problem and solution.

ENCD-3641 fix navigate to file download URI

---

src/encoded/schemas/source.json

Removes incorrect comment and updates source name to follow lab name convention.

ENCD-4008-fix-source-title

---

src/encoded/schemas/changelogs/user.md
src/encoded/schemas/user.json
src/encoded/tests/test_upgrade_user.py
src/encoded/upgrade/user.py

adding community to all users viewing_groups

ENCD-4016 adding community to users

---

src/encoded/loadxl.py
src/encoded/schemas/changelogs/reference_epigenome.md
src/encoded/schemas/reference_epigenome.json
src/encoded/static/components/dataset.js
src/encoded/static/components/experiment.js
src/encoded/static/components/file.js
src/encoded/static/components/typeutils.js
src/encoded/types/dataset.py
src/encoded/upgrade/dataset.py

ENCD-3889 add supersedes/superseded_by properties to ReferenceEpigenome object
Display those properties on the ReferenceEpigenome page

ENCD-3889 supersedes refepi

---

src/encoded/static/components/biosample.js
src/encoded/static/scss/encoded/modules/_visualize.scss

This is a tricky one. I took out the flex changes made by a prior developer. I could not see a strong reason why it was  needed in the first place and no other code seemed to use it.

ENCD-3364  fixed text and link button misalignment

---

src/encoded/schemas/changelogs/genetic_modification.md
src/encoded/schemas/genetic_modification.json
src/encoded/tests/data/inserts/genetic_modification.json
src/encoded/tests/test_schema_genetic_modification.py
src/encoded/tests/test_upgrade_genetic_modification.py
src/encoded/upgrade/genetic_modification.py

update the purpose of GM to include screening and renaming validation to be characterization

ENCD-4042 Update genetic mods for functional characterization experiments

---

src/encoded/tests/data/inserts/user.json

Added myself as a submitter in test.

ENCD-4049-added-myself-as-a-test-user

---

src/encoded/static/components/biosample.js
src/encoded/tests/data/inserts/user.json

@caseylitton This contain code to add me to user.json. This relates to this feature in that it helps me with testing locally.

ENCD-3883-add-pmi-data

---

npm-shrinkwrap.json
package.json
src/encoded/static/components/app.js
src/encoded/static/components/footer.js
src/encoded/static/scss/encoded/_layout.scss
webpack.config.js

Added link to privacy policy in auth0 login modal. Required an upgrade to the auth0 npm package version.

ENCD-4045 gdpr auth0

---

src/encoded/static/components/filegallery.js
src/encoded/static/scss/encoded/modules/_tables.scss

This reverts commit e52d2f9e358a196d6e3ffc8deacb026cc9ebc9dd.

Revert "ENCD-4048-update-publication-data-raw-file-table (#2273)"

---

src/encoded/tests/data/inserts/user.json

ENCD-4081 Add Yunhai as a submitter in local test.

---

src/encoded/schemas/file.json
src/encoded/types/base.py
src/encoded/types/user.py

ENCD-4078-remove-unused-statuses

---

src/encoded/tests/test_file_download.py
src/encoded/types/file.py

Will return 404 instead of ValueError now if file doesn't have external sheet with download location.

ENCD-3718-return-404-when-file-not-found

---

src/encoded/vis_defines.py
src/encoded/visualization.py

A lot of work git back and forth to fix this one line bug that shows up on a dataset in an illicit state.  Please make sure that the change in ENCD-4073 is not overwritten by this pull request.

ENCD-4040 vis index replicate conditional

---

cloud-config-elasticsearch.yml
src/encoded/commands/deploy.py

This replaces PR 
Kcl/remove data master node #2284

ENCD-4072 Remove es master from deployment

---

src/encoded/schemas/changelogs/organism.md
src/encoded/schemas/changelogs/platform.md
src/encoded/schemas/changelogs/source.md
src/encoded/schemas/changelogs/treatment.md
src/encoded/schemas/organism.json
src/encoded/schemas/platform.json
src/encoded/schemas/source.json
src/encoded/schemas/treatment.json
src/encoded/static/components/status.js
src/encoded/static/components/testdata/lot_review.js
src/encoded/static/components/testdata/source.js
src/encoded/static/components/testdata/source/aviva.js
src/encoded/tests/data/inserts/lab.json
src/encoded/tests/data/inserts/organism.json
src/encoded/tests/data/inserts/platform.json
src/encoded/tests/data/inserts/source.json
src/encoded/tests/data/inserts/treatment.json
src/encoded/tests/datafixtures.py
src/encoded/tests/test_upgrade_organism.py
src/encoded/tests/test_upgrade_platform.py
src/encoded/tests/test_upgrade_source.py
src/encoded/tests/test_upgrade_treatment.py
src/encoded/tests/test_views.py
src/encoded/upgrade/organism.py
src/encoded/upgrade/platform.py
src/encoded/upgrade/source.py
src/encoded/upgrade/treatment.py

Same as original ENCD-3776 but lab remains shared_status.

ENCD-3776-move-to-standard-status-no-lab

---

src/encoded/tests/test_key.py
src/encoded/tests/testing_views.py

This fixes encoded test now that SNO-41 is merged.

ENCD-4103 Fix tests broken by SNO-41

---

docs/region-search-viz-cache.rst
src/encoded/batch_download.py
src/encoded/commands/deploy.py
src/encoded/commands/generate_scored_snps.py
src/encoded/region_atlas.py
src/encoded/region_indexer.py
src/encoded/region_search.py
src/encoded/schemas/annotation.json
src/encoded/schemas/document.json
src/encoded/schemas/file.json
src/encoded/static/components/genome_browser.js
src/encoded/static/components/region_search.js
src/encoded/static/components/search.js
src/encoded/tests/data/inserts/experiment.json
src/encoded/tests/features/test_region_search.py
src/encoded/tests/test_indexing.py
src/encoded/vis_defines.py
src/encoded/visualization.py

This is the first development release for regulome updates.  This is a long running update so we're going to make a number of 'development releases' until we're ready to make a PR to encoded.  These PRs are going to a side branch called regulome-master.  
The code review process for the development releases should be light, looking for things that must be changed before QA.  We'll do a more thorough code review later on.

REG-39 Regulome Release 1

---

src/encoded/static/components/__tests__/dbxref-test.js
src/encoded/static/components/dbxref.js

1. Flybase changed their search url. This change reflects this update
2. Dataset and some other search criteria were removed. See the jira ticket for details if interested.

ENCD-4087-fixed-flybase-search

---

src/encoded/static/components/schema.js
src/encoded/static/scss/encoded/modules/_blocks.scss

It’s possible wranglers or associates will want to change the text during QA, but that should only affect what’s between the `<p>` tags.

ENCD-3903 add documentation for schema page

---

src/encoded/static/scss/encoded/modules/_facet.scss

ENCD-4074-toolip-overlay

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py

adjusting the audit for chip control to treat properly matched sets

ENCD-4108 audit matched

---

src/encoded/tests/test_status_trigger.py

ENCD-4143-add-assert-call-count

---

src/encoded/tests/test_status_trigger.py
src/encoded/types/__init__.py
src/encoded/types/antibody_lot.py
src/encoded/types/base.py
src/encoded/types/biosample.py
src/encoded/types/characterization.py
src/encoded/types/dataset.py
src/encoded/types/donor.py
src/encoded/types/experiment.py
src/encoded/types/file.py
src/encoded/types/genetic_modification.py
src/encoded/types/pipeline.py
src/encoded/types/quality_metric.py

Implements a method for releasing/deleting/revoking/archiving objects and their subobjects.

ENCD-4131-set-status-endpoint

---

src/encoded/loadxl.py
src/encoded/schemas/changelogs/gene.md
src/encoded/schemas/gene.json
src/encoded/search.py
src/encoded/static/components/dbxref.js
src/encoded/static/components/gene.js
src/encoded/static/components/index.js
src/encoded/static/components/search.js
src/encoded/tests/data/inserts/gene.json
src/encoded/types/gene.py

TBD
I haven't put any gene on it. I'll work on the genes for current targets. I'm not sure when I should load genes, now or after code review?
* ENCD-3997
- Add gene.json to schemas; adopted from target.json
- Add gene.py totypes;adopted from target.py
- Add gene to the Order array in loadxl.py
- Add sample data to test gene object; adopted from target.json
- Add changelog for the gene object
* ENCD-3998
- Embed and linkTo gene in target
- rev link to and linkFrom targets in gene
- Update target test data with gene embedded
- Update target changelog

ENCD-3997 Create Gene object

---

src/encoded/region_indexer.py

next release of regulome, has been QA'd

REG-38-parse-zero-length-SNP

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py

Adding an audit for missing RIN in RNA libraries

ENCD-4166 RIN internal action audit

---

CHANGES.rst

This reverts commit 817479901f8cec42b86f840fd28d14ba0bdffb58.

Revert accidental commits to change log

---

src/encoded/tests/features/matrix.feature
src/encoded/tests/features/test_matrix.py

@caseylitton ENCD-4038-bdd-matrix-tests-2 replaces ENCD-4038-bdd-matrix-tests. Would you have any trouble if I delete ENCD-4038-bdd-matrix-tests or you prefer I keep it?

ENCD-4038 Adding matrix bdd tests

---

src/encoded/tests/data/inserts/user.json

Added user objects for Casey, Jason, and Zack to the test user inserts.

ENCD-4160 Add Casey Jason Zack to user inserts

---

src/encoded/types/dataset.py
src/encoded/types/shared_calculated_properties.py

More efficient assay_term_id calculated property for FileSets and use of skip_calculated=true. This is joint PR with Snovault ticket.

ENCD-4153-alter-select-distinct-values

---

src/encoded/tests/data/inserts/user.json

I added myself to user.json so I can log in to local demos.

ENCD-4173 Add Paul to test user inserts

---

cloud-config-cluster.yml
cloud-config-elasticsearch.yml
cloud-config-no-es.yml
cloud-config.yml

https://encodedcc.atlassian.net/browse/ENCD-4196
This was becoming a nuisance.  Should have just removed comments and empty lines from all cloud-init files.
I did a quick test on the demo.  I'll be using this update all week building other clusters and demos for es worker stuff.

ENCD-4196 Reduce cloud init size

---

src/encoded/types/shared_calculated_properties.py

new PR to replace the one with problematic history of commits
Closed pr: https://github.com/ENCODE-DCC/encoded/pull/2412

ENCD-4206 calc prop rebased

---

src/encoded/audit/experiment.py
src/encoded/tests/test_audit_experiment.py

Adjusting the audit code to work with subsampling steps even without pipeline

ENCD-4202 fixing missing control audit

---

src/encoded/viewconfigs/auditview.py
src/encoded/viewconfigs/matrix.py
src/encoded/viewconfigs/summary.py
src/encoded/viewconfigs/views.py

[2nd] ENCD-3926 Search Refactor Rc Bug Fixes

---

src/encoded/static/components/__tests__/dbxref-test.js
src/encoded/static/components/dbxref.js

Updated the URL prefix for links to BDSC

ENCD-4176 fix BDSC links

---

src/encoded/tests/test_types_file.py
src/encoded/types/file.py

Exposes google_transfer and s3_uri calculated properties on released/archived/revoked files.

ENCD-4185-s3-public-url

---

src/encoded/region_indexer.py

I'm expecting this needs quite some going back and forth. But this is very important for regulome working properly.

REG-45 try handle some region index error.

---

src/encoded/static/components/region_search.js

adding navigate function so history is saved and back button works

ENCD-4256 Fix region search back button functionality

---

src/encoded/audit/biosample.py

changed from "term_id" to "detail" in line 79.

ENCD-4255-fix-biosample-audit-bug

---

npm-shrinkwrap.json
package.json
src/encoded/static/components/auditmatrix.js
src/encoded/static/components/matrix.js

ENCD-4281-fix-audit-text-message

---

src/encoded/static/components/antibody.js
src/encoded/static/components/biosample.js
src/encoded/static/components/donor.js
src/encoded/static/components/gene.js
src/encoded/static/components/target.js

ENCD-4321 Fix Javascript crash in v78rc1

---

buildout.cfg
ini-templates/base-template.ini
ini-templates/development-template.ini
src/encoded/tests/features/test_trackhubs.py
src/encoded/tests/test_indexing.py

https://github.com/ENCODE-DCC/snovault/pull/151

ENCD-4301 Refactor index UUID server

---

src/encoded/schemas/changelogs/treatment.md
src/encoded/schemas/treatment.json
src/encoded/tests/data/inserts/treatment.json
src/encoded/tests/test_types_treatment.py
src/encoded/tests/test_upgrade_treatment.py
src/encoded/types/__init__.py
src/encoded/upgrade/treatment.py

Remove lab from treatments to prevent submitters from adding/editing.

ENCD-4272-no-add-treatments

---

src/encoded/tests/data/inserts/user.json

Added Jennifer as a user test data insert

ENCD-4201-add-Jen-test-insert

---

src/encoded/types/experiment.py

Added the status facet to Experiment objects in Matrix view and AntibodyLot objects in Search view.

ENCD-4334 add status facet

---

buildout.cfg

ENCD-4371 Update to snovault 1.0.22

---

package-lock.json
package.json

ENCD-4423 Update dalliance to version 1.0

---

src/encoded/static/components/filegallery.js
src/encoded/static/components/vis_defines.js
src/encoded/vis_defines.py

Converted some FileGallery object properties that saved intermediate data into states to force a rerender that was missing. Also removed some code that was causing race conditions.

[2nd] ENCD-4325 Juicebox browser mods for annos

---

src/encoded/tests/data/inserts/user.json

ENCD-4402 user.json file edited to add Jennifer Z as a user.

ENCD-4402 Add Jennifer Z to submitters

---

src/encoded/types/antibody_lot.py

Corrected a line to "characterizations.characterization_reviews.biosample_ontology".

ENCD-4416 Revise audit_inherit list of AntibodyLots

---

buildout.cfg
src/encoded/commands/generate_ontology.py
src/encoded/docs/updating_ontologies.md

Added colon to organ slims, PLAC-seq to assay slims, directed uberon to most recent owl link, generated new ontology.json and buildout, updated docs

ENCD-4298 Ontology update colon and PLAC-seq

---

src/encoded/types/file.py

Indexer must be notified once bucket has been updated.

ENCD-4455-bucket-notify

---

src/encoded/audit/genetic_modification.py
src/encoded/tests/test_audit_genetic_modification.py

replaces https://github.com/ENCODE-DCC/encoded/pull/2568

ENCD-4429 Lower audit severity for missing reagents in GM

---

src/encoded/types/characterization.py

This reverts commit e56ae1409fc71b4ed20744556b641cdf0b8f75eb.

Revert "fixing view permissions on AB characterizations"

---

candidate.cfg

Points private bucket variable to private bucket and public bucket variable to public bucket.

ENCD-4475-fix-bucket-variables

---

.travis.yml
buildout.cfg
candidate.cfg
cloud-config-no-es.yml
cloud-config.yml
ini-templates/base-template.ini
ini-templates/development-template.ini
src/encoded/commands/deploy.py
src/encoded/region_indexer.py
src/encoded/tests/test_indexing.py
src/encoded/vis_indexer.py
test.cfg

only failed test admin user bdd test

SNO-73-ENCD-4456 Add uuid queue module

---

src/encoded/viewconfigs/matrix.py

ENCD-4353-Refactor-out-matrix-and-result

---

src/encoded/tests/test_audit_file.py
src/encoded/tests/test_types_file.py
src/encoded/types/file.py

Avoid incorrect file bucket audit on restricted and missing files.

ENCD-4505-fix-file-bucket-audit

---

src/encoded/static/components/search.js

Fix JavaScript error on Safari and Firefox
Evidently using "new Date()" causes non-deterministic behavior and using moment.js prevents this behavior

ENCD-4518 Fix javascript error for sorting dates

---

src/encoded/tests/test_audit_file.py

ENCD-4509-rc2-file-transfer-updates

---

src/encoded/schemas/changelogs/treatment.md
src/encoded/schemas/mixins.json

Added enum "stimulation" to treatment_type array in schema mixins.json treatment_classification.

ENCD-4469 Add stimulation to treatment type

---

src/encoded/tests/data/inserts/user.json

Corrected JIRA ticket number. Added new user for Meenakshi

ENCD-4521-add-insert-user-meenakshi

---

src/encoded/schemas/annotation.json
src/encoded/schemas/changelogs/annotation.md
src/encoded/tests/data/inserts/annotation.json
src/encoded/tests/datafixtures.py
src/encoded/tests/test_upgrade_dataset.py
src/encoded/upgrade/dataset.py

Added annotation_type enum 'imputation' and made annotation_type required.

ENCD-4489 add imputation annotation_type

---

buildout.cfg

https://github.com/ENCODE-DCC/snovault/pull/174

SNO-83 Rotate img attachment for EXIF

---

src/encoded/batch_download.py
src/encoded/static/components/cart/batch_download.js
src/encoded/tests/data/inserts/file.json
src/encoded/tests/test_batch_download.py

Quick fix for batch_download and metadata endpoint when plus is in file type.

ENCD-3642-fix-file-format-download

---

src/encoded/tests/test_status_trigger.py
src/encoded/types/base.py

This validates schema on status transition.

ENCD-4361-validate-schema-set-status

---

src/encoded/static/components/home.js
src/encoded/static/scss/encoded/modules/_home.scss

In case we hot fix this into v85.

ENCD-4628 Add a mechanism for a home-page banner

---

src/encoded/types/experiment.py

Rename 2 RNA assays to shorten the titles & make them more consistent

ENCD-4611 update 2 polyA assay titles

---

src/encoded/static/components/home.js

The key part of this is simply the use of `allowMultipleRequest` which lets outstanding GET requests complete even when parallel GET requests fail. Other changes are to allow the home page to update when logging in, in case the banner page has status "in progress" and you log in as admin; and to prevent submitters from seeing "in progress" banners.

ENCD-4642 Stop home banner truncation

---

src/encoded/tests/test_status_trigger.py
src/encoded/tests/test_types_file.py
src/encoded/types/file.py

Show cloud metadata for private files.

ENCD-4648-always-show-cloud-metadata

---

src/encoded/schemas/experiment.json
src/encoded/static/components/app.js
src/encoded/static/components/search.js
src/encoded/static/scss/encoded/modules/_facet.scss

We are replacing the `date_released` and `date_submitted` facets with one facet which has a toggle and allows you to select a date range using the `advancedQuery` parameter.

ENCD-4084 date selector facet

---

src/encoded/audit/experiment.py
src/encoded/schemas/award.json
src/encoded/schemas/changelogs/award.md
src/encoded/tests/test_audit_experiment.py

ENCD-4609 Exclude fccs institutional certification

---

.travis.yml

ENCD-4633 Update saucelabs connect version

---

src/encoded/schemas/changelogs/file.md
src/encoded/schemas/file.json
src/encoded/tests/data/inserts/file.json
src/encoded/tests/test_schema_file.py

Added 'database' to the list of enums for file_format on File.json. Updated the ChangeLog and added a test insert.

ENCD-4634 Add database to file_format

---

src/encoded/schemas/award.json
src/encoded/schemas/changelogs/award.md
src/encoded/tests/datafixtures.py
src/encoded/tests/test_audit_antibody_characterization.py
src/encoded/tests/test_upgrade_award.py
src/encoded/upgrade/award.py

The 'title' property is now required for Award objects.

ENCD-4682 Award title required

---

src/encoded/viewconfigs/auditview.py
src/encoded/viewconfigs/matrix.py
src/encoded/viewconfigs/summary.py

Make fields consistent between views.

ENCD-4762-make-search-fields-consistent

---

src/encoded/static/components/filegallery.js
src/encoded/static/scss/encoded/modules/_panels.scss

Reverting functionality to be like production for pages where 'hideGraph' is true.

ENCD-4761 Fix table display for non-anno and exp pages

---

src/encoded/static/components/experiment.js

ENCD-4811 Change breadcrumb pluralization

---

src/encoded/static/components/home.js
src/encoded/static/scss/encoded/modules/_home.scss

A demo is in early indexing at https://encd-4825-cbdc2908c-fytanaka.demo.encodedcc.org/ but doesn’t need to be indexed for this. I’m going to rename this demo once it has completed indexing.

ENCD-4825 Return Data Matrix button style and clean up CSS

---

src/encoded/static/components/award.js

The issue is that a function that mutated its argument in moment.js does not in dayjs.

ENCD-4871 Fix summary page experiment graph

---

src/encoded/tests/datafixtures.py
src/encoded/tests/test_audit_experiment.py
src/encoded/tests/test_types_experiment.py
src/encoded/types/experiment.py
src/encoded/types/shared_calculated_properties.py

Reverts ENCODE-DCC/encoded#2920 - ENCD-4833.  Code was functional but indexing was too slow.

[REVERT] ENCD-4833 replicates type calculated property update

---

src/encoded/audit/file.py

changed level of audit missing controlled by from not compliant to warning in audit/file.py

ENCD-4854 Change severity of missing controlled by

---

src/encoded/static/components/award.js

I increased the number of x-ticks because it seems the current limit is too low.

ENCD-4902-fix-graph-x-tick

---

package-lock.json
package.json
src/encoded/static/components/app.js
src/encoded/static/components/genome_browser.js
webpack.config.js

We want to load the Valis genome visualizer as a component.

ENCD-4722 install Valis as component

---

CHANGES.rst
setup.py

1.	ENCD-4924 fix bugs in moving controls (#3001)
2.	ENCD-4928-run-npm-once (#3002)
3.	ENCD-4925-increase-circle-es-heap (#2999)
4.	ENCD-4895-adjust-long-read-RNA-audit (#2982)
5.	ENCD-4920-update-snovault-1.0.37 (#2997)
6.	ENCD-3336-Upgrade-postgres-11 (#2976)  
7.	ENCD-4892 region search refresh (#2978)
8.	ENCD-4861 add enum to user groups(#2964)
9.	ENCD-4849-fix-description-misalignment-in-docs (#2958)
10.	ENCD-4840-Add-Donor-accession-boost-value (#2975)
11.	ENCD-4674 move Control from Target to Experiment (#2866)
12.	ENCD-4894 Exclude long read RNA-seq from RNA fragment size audit and add tests for missing read_length (#2969)
13.	ENCD-4900 Add status check for matching md5 sum audit (#2972)
14.	ENCD-4903-image-update (#2983)
15.	[HOTFIX] SNO-120-stream-large-json (#2980)
16.	ENCD-4885 …

Update to 92.0

---

src/encoded/tests/data/inserts/user.json

I copy-pasted Bonita's user schema, substituted my own details, and removed the uuid line in user.json

ENCD-4904-add-ingrid-as-user

---

.circleci/config.yml

Uses about half of circle compute resources, completes in same amount of time.

ENCD-4935-reduce-compute

---

src/encoded/schemas/experiment.json

removed library treatment facet from experiment schema

ENCD-4933-remove-library-treatment-facet

---

cloud-config/config-build-files/cc-parts/CC_BOOTCMD.yml

Going to build a machine and try a load test.

ENCD-4908-turn-on-swap-in-deployment

---

src/encoded/schemas/biosample.json
src/encoded/schemas/genetic_modification.json

I think there will be more.  But I don't want to leave this open over the holiday and forget about it.  I kept this to items that I think are just grammar and syntax. The ticket is ENCD-4974

ENCD-4974-cricket-typo-fixes

---

src/encoded/loadxl.py
src/encoded/schemas/changelogs/single_cell_rna_series.md
src/encoded/schemas/single_cell_rna_series.json
src/encoded/static/components/dataset.js
src/encoded/static/components/search.js
src/encoded/tests/data/inserts/single_cell_rna_series.json
src/encoded/tests/test_types_series.py
src/encoded/types/dataset.py

added sc rNA series schema
adding an insert
added test
js search
updating JS more

ENCD-4922 single cell RNA series

---

CHANGES.rst
setup.py

Update to 94.0

---

src/encoded/static/components/schema.js

We want to display "anyOf" and "oneOf" schemas on the formatted schema pages.

ENCD-4956-add-content-to-schema

---

src/encoded/schemas/changelogs/file.md
src/encoded/schemas/file.json
src/encoded/tests/data/inserts/file.json

adding index of
adding index reads output type
adding dependencies
updating insert
fixing loadxl and inserts

ENCD-4995 adding index reads

---

src/encoded/static/components/genome_browser.js
src/encoded/static/scss/encoded/modules/_genome_browser.scss
src/encoded/static/scss/fontawesome/_icons.scss

Adds a reset button to the Valis genome browser so that users can return to the initial browser position.

ENCD-5032-add-reset-to-browser

---

src/encoded/static/components/app.js

ENCD-5086-remove-chip-seq-matrix-from-menu

---

package-lock.json

Not sure there's a lot to review, as much as to note the massive change to package-lock.json.
Indexed demo at: https://encd-5091-rebuild-lock-pr1-fytanaka.demo.encodedcc.org/

ENCD-5091 Rebuilt package-lock.json

---

src/encoded/schemas/biosample_type.json
src/encoded/schemas/changelogs/biosample_type.md
src/encoded/static/components/__tests__/dbxref-test.js
src/encoded/static/components/dbxref.js

Ok, this is a pretty simple fix.  However, our test environments are in different version states. So, I humbly ask that someone run this with your suite of tests. If there is any error at all, I will push through with getting a test environment up for myself.

ENCD-5075 Adding the change for depmap
